export const companies = [
  {
    slug: "safaricom-plc",
    name: "Safaricom PLC",
    initials: "SC",
    logoColor: "#00a254",
    industry: "Telecommunications",
    location: "Nairobi",
    size: "5,000+",
    openJobs: 12,
    isVerified: true,
    description: "Leading telecommunications provider in Kenya, home of M-PESA.",
  },
  {
    slug: "equity-bank",
    name: "Equity Bank Kenya",
    initials: "EB",
    logoColor: "#e65100",
    industry: "Banking & Finance",
    location: "Nairobi",
    size: "10,000+",
    openJobs: 11,
    isVerified: true,
    description: "One of Kenya's largest banks with operations across East Africa.",
  },
  {
    slug: "kcb-group",
    name: "KCB Group",
    initials: "KC",
    logoColor: "#1a237e",
    industry: "Banking & Finance",
    location: "Nairobi",
    size: "8,000+",
    openJobs: 9,
    isVerified: true,
    description: "The largest commercial bank in Kenya by asset base.",
  },
  {
    slug: "kpmg-kenya",
    name: "KPMG East Africa",
    initials: "KP",
    logoColor: "#00338d",
    industry: "Consulting",
    location: "Nairobi",
    size: "1,000+",
    openJobs: 7,
    isVerified: true,
    description: "One of the Big Four accounting firms providing audit, tax, and advisory services.",
  },
  {
    slug: "unep-nairobi",
    name: "UNEP Nairobi",
    initials: "UN",
    logoColor: "#00796b",
    industry: "NGO & Development",
    location: "Nairobi",
    size: "2,000+",
    openJobs: 5,
    isVerified: true,
    description: "United Nations Environment Programme headquartered in Nairobi, Kenya.",
  },
  {
    slug: "safaricom-mpesa",
    name: "M-PESA (Safaricom)",
    initials: "MP",
    logoColor: "#00c853",
    industry: "FinTech",
    location: "Nairobi",
    size: "500+",
    openJobs: 6,
    isVerified: true,
    description: "World-leading mobile money service transforming financial inclusion in Africa.",
  },
  {
    slug: "kenya-power",
    name: "Kenya Power",
    initials: "KP",
    logoColor: "#2e7d32",
    industry: "Energy & Utilities",
    location: "Nairobi",
    size: "7,000+",
    openJobs: 8,
    isVerified: true,
    description: "National electricity transmission and distribution utility company.",
  },
  {
    slug: "ncba-group",
    name: "NCBA Group",
    initials: "NC",
    logoColor: "#b71c1c",
    industry: "Banking & Finance",
    location: "Nairobi",
    size: "3,000+",
    openJobs: 4,
    isVerified: false,
    description: "A leading commercial bank formed from the merger of NIC Group and CBA.",
  },
  {
    slug: "britam",
    name: "Britam Holdings",
    initials: "BR",
    logoColor: "#0d47a1",
    industry: "Insurance",
    location: "Nairobi",
    size: "1,500+",
    openJobs: 5,
    isVerified: true,
    description: "Leading diversified financial services group in East Africa.",
  },
  {
    slug: "eabl",
    name: "East African Breweries",
    initials: "EA",
    logoColor: "#c62828",
    industry: "Manufacturing",
    location: "Nairobi",
    size: "1,200+",
    openJobs: 3,
    isVerified: true,
    description: "Leading beverage alcohol company in East Africa, listed on NSE.",
  },
];

export const industries = [
  "All Industries",
  "Banking & Finance",
  "Telecommunications",
  "Consulting",
  "IT & Technology",
  "NGO & Development",
  "Government",
  "Healthcare",
  "Manufacturing",
  "Education",
  "Energy & Utilities",
  "Insurance",
  "FinTech",
];

export const companySizes = [
  "All Sizes",
  "1-50 employees",
  "51-200 employees",
  "201-500 employees",
  "501-1000 employees",
  "1000+ employees",
];

export const locations = [
  "All Locations",
  "Nairobi",
  "Mombasa",
  "Kisumu",
  "Nakuru",
  "Remote",
];

export const featuredCompanies = companies.filter((c) => c.openJobs >= 9).slice(0, 5);

export const browseIndustries = [
  { name: "Banking & Finance", count: 18 },
  { name: "IT & Technology", count: 22 },
  { name: "Government", count: 24 },
  { name: "NGO & Development", count: 31 },
  { name: "Telecommunications", count: 5 },
  { name: "Healthcare", count: 12 },
];
