export const company = {
  slug: "safaricom-plc",
  name: "Safaricom PLC",
  initials: "SC",
  logoColor: "#00a254",
  tagline: "Transforming Lives. Connecting People.",
  industry: "Telecommunications",
  location: "Nairobi, Kenya",
  fullAddress: "Safaricom House, Waiyaki Way, Westlands, Nairobi",
  size: "5,000+",
  employeeCount: "5,000+",
  founded: 1999,
  website: "https://www.safaricom.co.ke",
  tickerSymbol: "SCOM",
  type: "Listed Company",
  isVerified: true,
  description: [
    "Safaricom PLC is Kenya's leading telecommunications company, serving over 40 million customers. Best known for pioneering M-PESA, the revolutionary mobile money service that has transformed financial inclusion across East Africa and inspired similar services globally.",
    "As a technology company at its core, Safaricom continues to drive innovation in areas including 4G/LTE connectivity, cloud services, IoT solutions, and digital financial services. The company is committed to its purpose of transforming lives and connecting people.",
    "Safaricom is listed on the Nairobi Securities Exchange (NSE) and is a constituent of the NSE 20 Share Index. The company has consistently been ranked as Kenya's most valuable brand and one of the best employers in East Africa.",
  ],
  stats: {
    openJobs: 12,
    totalHires: "500+",
    employees: "5,000+",
  },
  keyDetails: [
    { label: "Industry", value: "Telecommunications" },
    { label: "Founded", value: "1999" },
    { label: "Size", value: "5,000+ employees" },
    { label: "Location", value: "Nairobi, Kenya" },
    { label: "Website", value: "safaricom.co.ke", href: "https://www.safaricom.co.ke" },
    { label: "Type", value: "NSE Listed (SCOM)" },
  ],
};

export const companyJobs = [
  {
    title: "Senior Software Engineer",
    slug: "senior-software-engineer-safaricom",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Senior",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: "2026-03-15T09:00:00+03:00",
    deadline: "2026-04-15T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Product Manager — M-PESA",
    slug: "product-manager-mpesa",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Mid-Senior",
    isNew: true,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-18T09:00:00+03:00",
    deadline: "2026-04-20T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Data Analyst",
    slug: "data-analyst-safaricom",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Mid",
    isNew: false,
    isFeatured: false,
    isUrgent: true,
    publishedAt: "2026-03-10T09:00:00+03:00",
    deadline: "2026-04-01T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Network Engineer",
    slug: "network-engineer-safaricom",
    location: "Mombasa",
    jobType: "Full-Time",
    experienceLevel: "Mid",
    isNew: false,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-08T09:00:00+03:00",
    deadline: "2026-04-10T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Cybersecurity Analyst",
    slug: "cybersecurity-analyst-safaricom",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Mid-Senior",
    isNew: true,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-19T09:00:00+03:00",
    deadline: "2026-04-18T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Marketing Communications Manager",
    slug: "marketing-comms-manager-safaricom",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Senior",
    isNew: false,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-05T09:00:00+03:00",
    deadline: "2026-04-05T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "Finance Graduate Trainee",
    slug: "finance-graduate-trainee-safaricom",
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Entry",
    isNew: false,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-12T09:00:00+03:00",
    deadline: "2026-04-25T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
  {
    title: "IT Support Intern",
    slug: "it-support-intern-safaricom",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    isNew: false,
    isFeatured: false,
    isUrgent: false,
    publishedAt: "2026-03-14T09:00:00+03:00",
    deadline: "2026-04-30T23:59:00+03:00",
    company: { name: "Safaricom PLC", slug: "safaricom-plc", logoColor: "#00a254", initials: "SC", isVerified: true },
  },
];

export const similarCompanies = [
  { slug: "airtel-kenya", name: "Airtel Kenya", initials: "AK", logoColor: "#e4002b", openJobs: 6 },
  { slug: "kcb-group", name: "KCB Group", initials: "KC", logoColor: "#1a237e", openJobs: 9 },
  { slug: "equity-bank", name: "Equity Bank Kenya", initials: "EB", logoColor: "#e65100", openJobs: 11 },
  { slug: "ncba-group", name: "NCBA Group", initials: "NC", logoColor: "#b71c1c", openJobs: 4 },
  { slug: "kenya-power", name: "Kenya Power", initials: "KP", logoColor: "#2e7d32", openJobs: 7 },
];

export const browseIndustries = [
  { name: "Telecommunications", count: 5 },
  { name: "Banking & Finance", count: 18 },
  { name: "IT & Technology", count: 22 },
  { name: "Government", count: 24 },
  { name: "NGO & Development", count: 31 },
  { name: "Healthcare", count: 12 },
];
