// Mock data for the Jobs Listing page

export const allJobs = [
  {
    id: 1,
    slug: "senior-software-engineer-safaricom-plc",
    title: "Senior Software Engineer",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-15",
    isRemote: false,
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 2,
    slug: "marketing-director-equity-bank",
    title: "Marketing Director",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Marketing",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-20",
    isRemote: false,
    company: {
      name: "Equity Bank Kenya",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
  },
  {
    id: 3,
    slug: "data-scientist-kcb-group",
    title: "Data Scientist",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-10",
    isRemote: true,
    company: {
      name: "KCB Group",
      slug: "kcb-group",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
  {
    id: 4,
    slug: "engineer-trainee-kenya-power",
    title: "Engineer Trainee",
    location: "Nationwide",
    jobType: "Internship",
    experienceLevel: "Entry",
    category: "Engineering",
    isFeatured: false,
    isNew: false,
    isUrgent: true,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-04-20",
    isRemote: false,
    company: {
      name: "Kenya Power",
      slug: "kenya-power",
      logoColor: "#059669",
      isVerified: false,
    },
  },
  {
    id: 5,
    slug: "software-engineer-backend-java-safaricom",
    title: "Software Engineer — Backend (Java)",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Technology",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-08",
    isRemote: false,
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 6,
    slug: "graphic-design-intern-ogilvy-kenya",
    title: "Graphic Design Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    category: "Creative Design",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-01",
    isRemote: false,
    company: {
      name: "Ogilvy Kenya",
      slug: "ogilvy-kenya",
      logoColor: "#e74c3c",
      isVerified: false,
    },
  },
  {
    id: 7,
    slug: "accountant-county-government-kiambu",
    title: "Accountant",
    location: "Kiambu",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Finance & Accounting",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-05",
    isRemote: false,
    company: {
      name: "County Government of Kiambu",
      slug: "county-gov-kiambu",
      logoColor: "#2563eb",
      isVerified: false,
    },
  },
  {
    id: 8,
    slug: "customer-service-representative-mombasa",
    title: "Customer Service Representative",
    location: "Mombasa",
    jobType: "Full-time",
    experienceLevel: "Entry",
    category: "Customer Service",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-04-28",
    isRemote: false,
    company: {
      name: "CCK Call Centres",
      slug: "cck-call-centres",
      logoColor: "#8b5cf6",
      isVerified: false,
    },
  },
  {
    id: 9,
    slug: "project-manager-unep-nairobi",
    title: "Project Manager — Climate Adaptation",
    location: "Nairobi",
    jobType: "Contract",
    experienceLevel: "Senior",
    category: "NGO",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-25",
    isRemote: true,
    company: {
      name: "UNEP Kenya",
      slug: "unep-kenya",
      logoColor: "#009688",
      isVerified: true,
    },
  },
  {
    id: 10,
    slug: "nursing-officer-kenyatta-hospital",
    title: "Nursing Officer — ICU",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Healthcare",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-12",
    isRemote: false,
    company: {
      name: "Kenyatta National Hospital",
      slug: "kenyatta-hospital",
      logoColor: "#dc2626",
      isVerified: true,
    },
  },
  {
    id: 11,
    slug: "product-manager-m-pesa-safaricom",
    title: "Product Manager — M-PESA",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Technology",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-18",
    isRemote: false,
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 12,
    slug: "head-of-digital-banking-equity",
    title: "Head of Digital Banking",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Manager",
    category: "Finance & Accounting",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-22",
    isRemote: false,
    company: {
      name: "Equity Bank",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
  },
  {
    id: 13,
    slug: "risk-analyst-kcb-group",
    title: "Risk Analyst",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Finance & Accounting",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-14",
    isRemote: false,
    company: {
      name: "KCB Group",
      slug: "kcb-group",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
  {
    id: 14,
    slug: "kra-internship-programme-2026",
    title: "Internship Programme 2026",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    category: "Government",
    isFeatured: false,
    isNew: false,
    isUrgent: true,
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-04-18",
    isRemote: false,
    company: {
      name: "Kenya Revenue Authority",
      slug: "kra",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
  {
    id: 15,
    slug: "finance-intern-britam",
    title: "Finance Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    category: "Finance & Accounting",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-04-30",
    isRemote: false,
    company: {
      name: "Britam Holdings",
      slug: "britam",
      logoColor: "#7c3aed",
      isVerified: false,
    },
  },
  {
    id: 16,
    slug: "it-support-intern-ncba",
    title: "IT Support Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    category: "Technology",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-03",
    isRemote: false,
    company: {
      name: "NCBA Group",
      slug: "ncba-group",
      logoColor: "#059669",
      isVerified: true,
    },
  },
  {
    id: 17,
    slug: "audit-associate-pwc-kenya",
    title: "Audit Associate",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Entry",
    category: "Finance & Accounting",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-06",
    isRemote: false,
    company: {
      name: "PwC Kenya",
      slug: "pwc-kenya",
      logoColor: "#7c3aed",
      isVerified: true,
    },
  },
  {
    id: 18,
    slug: "branch-manager-kisumu-equity",
    title: "Branch Manager — Kisumu",
    location: "Kisumu",
    jobType: "Full-time",
    experienceLevel: "Senior",
    category: "Finance & Accounting",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-20",
    isRemote: false,
    company: {
      name: "Equity Bank",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
  },
  {
    id: 19,
    slug: "supply-chain-officer-mombasa",
    title: "Supply Chain Officer",
    location: "Mombasa",
    jobType: "Full-time",
    experienceLevel: "Mid",
    category: "Logistics",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-05-09",
    isRemote: false,
    company: {
      name: "Maersk Kenya",
      slug: "maersk-kenya",
      logoColor: "#0369a1",
      isVerified: true,
    },
  },
  {
    id: 20,
    slug: "secondary-school-teacher-nakuru",
    title: "Secondary School Teacher — Mathematics",
    location: "Nakuru",
    jobType: "Full-time",
    experienceLevel: "Entry",
    category: "Education",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    deadline: "2026-04-25",
    isRemote: false,
    company: {
      name: "Ministry of Education",
      slug: "ministry-of-education",
      logoColor: "#1e40af",
      isVerified: true,
    },
  },
];

// Filter options — values match API query param enum format
export const filterCategories = [
  { label: "Technology", value: "TECHNOLOGY", count: 342 },
  { label: "Finance & Accounting", value: "FINANCE_ACCOUNTING", count: 256 },
  { label: "Engineering", value: "ENGINEERING", count: 189 },
  { label: "Healthcare", value: "HEALTHCARE", count: 234 },
  { label: "Education", value: "EDUCATION", count: 167 },
  { label: "Marketing", value: "MARKETING_COMMUNICATIONS", count: 198 },
  { label: "Government", value: "GOVERNMENT_PUBLIC_SECTOR", count: 412 },
  { label: "NGO & Development", value: "NONPROFIT", count: 156 },
  { label: "Creative & Design", value: "CREATIVE_DESIGN", count: 89 },
  { label: "Customer Service", value: "CUSTOMER_SERVICE", count: 134 },
  { label: "Logistics & Supply Chain", value: "SUPPLY_CHAIN", count: 98 },
  { label: "Legal", value: "LEGAL", count: 76 },
];

export const filterJobTypes = [
  { label: "Full-time", value: "FULL_TIME", count: 856 },
  { label: "Part-time", value: "PART_TIME", count: 124 },
  { label: "Contract", value: "CONTRACT", count: 98 },
  { label: "Internship", value: "INTERNSHIP", count: 234 },
  { label: "Remote", value: "Remote", count: 67 },
];

export const filterExperienceLevels = [
  { label: "Entry Level", value: "ENTRY", count: 445 },
  { label: "Mid Level", value: "MID", count: 523 },
  { label: "Senior Level", value: "SENIOR", count: 287 },
  { label: "Manager/Director", value: "MANAGER", count: 124 },
];

export const filterLocations = [
  { label: "Nairobi", value: "Nairobi", count: 1245 },
  { label: "Mombasa", value: "Mombasa", count: 234 },
  { label: "Kisumu", value: "Kisumu", count: 167 },
  { label: "Nakuru", value: "Nakuru", count: 134 },
  { label: "Remote", value: "Remote", count: 89 },
  { label: "Nationwide", value: "Nationwide", count: 45 },
];

export const trendingJobsSidebar = [
  {
    title: "Product Manager — M-PESA",
    slug: "product-manager-m-pesa-safaricom",
    company: "Safaricom PLC",
    location: "Nairobi",
    logoColor: "#00a254",
  },
  {
    title: "Branch Manager — Kisumu",
    slug: "branch-manager-kisumu-equity",
    company: "Equity Bank",
    location: "Kisumu",
    logoColor: "#f59e0b",
  },
  {
    title: "Audit Associate",
    slug: "audit-associate-pwc",
    company: "PwC Kenya",
    location: "Nairobi",
    logoColor: "#7c3aed",
  },
  {
    title: "Data Engineer",
    slug: "data-engineer-kcb",
    company: "KCB Group",
    location: "Nairobi",
    logoColor: "#1a56db",
  },
  {
    title: "Nursing Officer — ICU",
    slug: "nursing-officer-kenyatta-hospital",
    company: "Kenyatta National Hospital",
    location: "Nairobi",
    logoColor: "#dc2626",
  },
];

export const popularTags = [
  "CPA-K",
  "IFRS",
  "Excel",
  "QuickBooks",
  "Banking",
  "Audit",
  "Payroll",
  "Sage",
  "Python",
  "Java",
  "AWS",
  "Agile",
];
