// ============================================================
// Phase 7c — Job Listings Seed Data
// ============================================================
// ~100 jobs across all 23 hub categories
// Run separately or integrate into main seed.js
// ============================================================

function makeSlug(title, company) {
  const t = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
  return `${t}-at-${company}`;
}

function htmlDesc(about, requirements, responsibilities, highlights) {
  return `
<h3>About the Role</h3>
<p>${about}</p>

<h3>Responsibilities</h3>
<ul>${responsibilities.map(r => `<li>${r}</li>`).join('\n')}</ul>

<h3>Requirements</h3>
<ul>${requirements.map(r => `<li>${r}</li>`).join('\n')}</ul>

<h3>What We Offer</h3>
<ul>${highlights.map(h => `<li>${h}</li>`).join('\n')}</ul>
`.trim();
}

const JOBS = [
  // ═══════════════════════════════════════
  // TECHNOLOGY (8 jobs)
  // ═══════════════════════════════════════
  {
    title: "Senior Full Stack Developer",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 180000, salaryMax: 280000, showSalary: true,
    isFeatured: true,
    about: "Lead the development of customer-facing web and mobile applications serving over 40 million Safaricom customers. You will architect scalable microservices and mentor a team of 6 developers working on M-Pesa integrations, USSD platforms, and the MySafaricom App.",
    requirements: ["Bachelor's degree in Computer Science or equivalent", "5+ years experience with React, Node.js, and cloud services (AWS/Azure)", "Experience with microservices architecture and RESTful API design", "Strong understanding of mobile app development (React Native or Flutter)", "Knowledge of payment systems and financial technology"],
    responsibilities: ["Architect and develop scalable web and mobile applications", "Lead code reviews and maintain high code quality standards", "Collaborate with product managers and UX designers", "Mentor junior developers and conduct technical interviews", "Participate in on-call rotation for production systems"],
    highlights: ["Health insurance for self and family", "Performance-based annual bonus", "Flexible hybrid work arrangement", "Professional development budget (KSh 200,000/year)", "Employee stock purchase plan"],
    deadlineDays: 21,
  },
  {
    title: "Backend Engineer — Payments Platform",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 120000, salaryMax: 180000, showSalary: true,
    about: "Join the M-Pesa engineering team to build and optimize backend systems that process millions of daily transactions. You'll work with Java, Kafka, and PostgreSQL to ensure the reliability and scalability of Africa's largest mobile money platform.",
    requirements: ["3+ years backend development experience", "Proficiency in Java or Go", "Experience with distributed systems and message queues (Kafka, RabbitMQ)", "Understanding of database design and optimization", "Familiarity with CI/CD pipelines and containerization (Docker/K8s)"],
    responsibilities: ["Design and implement payment processing microservices", "Optimize database queries for high-throughput transaction processing", "Write unit and integration tests", "Monitor and troubleshoot production issues", "Document APIs and system architecture"],
    highlights: ["Competitive salary with annual increments", "M-Pesa staff benefits", "Health and dental insurance", "Paid annual leave (24 days)", "Training and certification sponsorship"],
    deadlineDays: 14,
  },
  {
    title: "React Native Mobile Developer",
    companySlug: "andela-kenya",
    location: "Pinewood Place, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 150000, salaryMax: 220000, showSalary: true,
    isFeatured: true,
    about: "Andela is looking for a skilled React Native developer to join our engineering team. You will build cross-platform mobile applications for Andela's internal tools and client-facing products, working with engineers distributed across Africa and the US.",
    requirements: ["3+ years of mobile development experience", "Strong proficiency in React Native and TypeScript", "Experience with state management (Redux, MobX, or Zustand)", "Familiarity with native iOS and Android development", "Excellent communication skills for remote collaboration"],
    responsibilities: ["Develop and maintain React Native mobile applications", "Integrate REST APIs and GraphQL endpoints", "Optimize app performance across devices", "Write comprehensive tests (Jest, Detox)", "Participate in agile ceremonies with distributed team"],
    highlights: ["Remote-first work culture", "Access to Andela's global talent network", "Hardware and internet stipend", "Annual learning budget", "Stock options"],
    deadlineDays: 30,
  },
  {
    title: "Data Scientist",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 200000, salaryMax: 300000, showSalary: true,
    about: "Leverage data to drive business decisions for Kenya's largest telecom. You will build predictive models for customer churn, network optimization, and revenue forecasting, working with datasets spanning millions of subscribers.",
    requirements: ["Master's degree in Data Science, Statistics, or related field", "4+ years experience in data science or machine learning", "Proficiency in Python (pandas, scikit-learn, TensorFlow)", "Experience with big data tools (Spark, Hadoop, or similar)", "Strong SQL skills and experience with data warehousing"],
    responsibilities: ["Build predictive models for business KPIs", "Design and analyze A/B tests", "Create dashboards and reports for senior leadership", "Collaborate with data engineers on data pipeline optimization", "Present findings to non-technical stakeholders"],
    highlights: ["Executive-level visibility and impact", "Access to cutting-edge data infrastructure", "International conference attendance sponsorship", "Competitive compensation package", "Relocation support available"],
    deadlineDays: 21,
  },
  {
    title: "DevOps Engineer",
    companySlug: "andela-kenya",
    location: "Remote — Kenya",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    isRemote: true,
    salaryMin: 130000, salaryMax: 190000, showSalary: true,
    about: "Andela seeks a DevOps Engineer to design and maintain cloud infrastructure supporting engineering teams across Africa. You will work with AWS, Terraform, and Kubernetes to ensure 99.9% uptime for critical systems.",
    requirements: ["3+ years DevOps/SRE experience", "Strong AWS or GCP expertise", "Experience with Infrastructure as Code (Terraform, CloudFormation)", "Proficiency with container orchestration (Kubernetes, Docker)", "Knowledge of monitoring tools (Datadog, Prometheus, Grafana)"],
    responsibilities: ["Design and implement CI/CD pipelines", "Manage cloud infrastructure using IaC", "Implement monitoring, alerting, and incident response", "Automate infrastructure provisioning and scaling", "Conduct capacity planning and cost optimization"],
    highlights: ["Fully remote position", "Flexible working hours", "Annual learning and development budget", "Monthly internet stipend", "Access to Andela's engineering community"],
    deadlineDays: 28,
  },
  {
    title: "Software Engineering Intern",
    companySlug: "moringa-school",
    location: "Ngong Road, Nairobi",
    category: "TECHNOLOGY",
    jobType: "INTERNSHIP",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    about: "Moringa School is offering a 6-month software engineering internship for recent graduates. You will work on real-world projects, receive mentorship from senior developers, and gain hands-on experience in web development technologies.",
    requirements: ["Recent graduate with a degree in Computer Science, IT, or related field", "Basic knowledge of HTML, CSS, and JavaScript", "Passion for software development and learning", "Strong problem-solving skills", "Available for 6 months full-time"],
    responsibilities: ["Build web applications using React and Node.js", "Participate in daily standups and sprint planning", "Write clean, well-documented code", "Contribute to open-source projects", "Present progress in demo sessions"],
    highlights: ["Monthly stipend of KSh 25,000", "Mentorship from industry professionals", "Certificate upon completion", "Potential full-time placement", "Free access to Moringa's learning platform"],
    deadlineDays: 7,
  },
  {
    title: "Cybersecurity Analyst",
    companySlug: "kenya-power",
    location: "Parklands, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 160000, showSalary: true,
    about: "Protect Kenya Power's critical infrastructure from cyber threats. You will monitor security systems, conduct vulnerability assessments, and implement security controls to safeguard the national electricity grid's digital systems.",
    requirements: ["Bachelor's degree in Cybersecurity, Computer Science, or related field", "3+ years in cybersecurity or information security", "Relevant certifications (CEH, CISSP, or CompTIA Security+)", "Experience with SIEM tools and penetration testing", "Knowledge of ICS/SCADA security is a plus"],
    responsibilities: ["Monitor and respond to security incidents", "Conduct vulnerability assessments and penetration tests", "Implement and maintain security policies", "Prepare security reports and risk assessments", "Train staff on security awareness"],
    highlights: ["Job security in a critical national utility", "Health insurance for family", "Pension scheme", "Housing allowance", "Training and certification sponsorship"],
    deadlineDays: 14,
  },
  {
    title: "QA Automation Engineer",
    companySlug: "airtel-kenya",
    location: "Muthaiga, Nairobi",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 90000, salaryMax: 140000, showSalary: true,
    about: "Join Airtel Kenya's digital team to ensure quality across mobile apps, web portals, and USSD services. You will design and implement automated testing frameworks and work closely with development teams to maintain high-quality standards.",
    requirements: ["3+ years in QA/Testing roles", "Experience with test automation frameworks (Selenium, Cypress, Appium)", "Proficiency in at least one programming language (Python, Java, or JavaScript)", "Experience with API testing (Postman, REST Assured)", "Knowledge of CI/CD integration for automated tests"],
    responsibilities: ["Design and implement automated test suites", "Perform regression, integration, and performance testing", "Report and track defects using JIRA", "Collaborate with developers to resolve issues", "Maintain test documentation and test plans"],
    highlights: ["Telecom industry experience", "Competitive salary package", "Medical and life insurance", "Staff data and voice benefits", "Professional development opportunities"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // FINANCE & ACCOUNTING (7 jobs)
  // ═══════════════════════════════════════
  {
    title: "Senior Financial Analyst",
    companySlug: "equity-bank-kenya",
    location: "Upper Hill, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 150000, salaryMax: 220000, showSalary: true,
    isFeatured: true,
    about: "Equity Bank is seeking a Senior Financial Analyst to join its Corporate Finance team. You will lead financial modeling, prepare board-level reports, and provide strategic recommendations on lending, investment, and capital allocation decisions.",
    requirements: ["CPA-K or ACCA qualification", "Bachelor's degree in Finance, Accounting, or Economics", "5+ years in financial analysis or corporate finance", "Advanced Excel and financial modeling skills", "Experience with ERP systems (SAP, Oracle, or Core Banking)"],
    responsibilities: ["Prepare financial models for investment decisions", "Analyze financial statements and performance metrics", "Develop forecasts and budgets for business units", "Present financial analysis to senior management", "Support audit and regulatory reporting"],
    highlights: ["Performance-based annual bonus", "Career progression to management roles", "Comprehensive health insurance", "Education reimbursement for MBA/CFA", "Staff banking benefits with preferential rates"],
    deadlineDays: 21,
  },
  {
    title: "Audit Associate",
    companySlug: "kpmg-east-africa",
    location: "Upper Hill, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 70000, salaryMax: 100000, showSalary: true,
    about: "KPMG East Africa is hiring Audit Associates to join its growing audit practice. You will work on engagements for listed companies, multinational corporations, and government entities, gaining exposure to diverse industries and complex audit procedures.",
    requirements: ["Bachelor's degree in Accounting, Finance, or related field", "CPA-K Section 4 completed or in progress", "Strong analytical and problem-solving skills", "Excellent written and verbal communication", "Proficiency in Microsoft Office suite"],
    responsibilities: ["Execute audit procedures for assigned clients", "Prepare working papers and audit documentation", "Assist in planning and risk assessment", "Communicate findings to audit managers and partners", "Participate in fieldwork across Kenya"],
    highlights: ["Big Four firm experience", "Structured career progression", "CPA exam support and study leave", "Exposure to diverse industries", "International secondment opportunities"],
    deadlineDays: 14,
  },
  {
    title: "Credit Risk Manager",
    companySlug: "kcb-group",
    location: "Kenyatta Avenue, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 180000, salaryMax: 250000, showSalary: true,
    about: "KCB Group is looking for an experienced Credit Risk Manager to oversee credit risk assessment across its East African operations. You will develop credit policies, manage the credit scoring model, and ensure regulatory compliance with CBK guidelines.",
    requirements: ["Master's degree in Finance, Risk Management, or related field", "7+ years in credit risk management within banking", "Strong knowledge of CBK prudential guidelines", "Experience with credit scoring models and analytics", "Professional certification (FRM or CFA preferred)"],
    responsibilities: ["Develop and maintain credit risk policies", "Oversee credit scoring and rating models", "Review and approve credit facilities above threshold", "Prepare credit risk reports for the Board", "Ensure compliance with regulatory requirements"],
    highlights: ["Regional role with East African exposure", "Executive-level compensation", "Car allowance and fuel card", "Pension and life insurance", "Annual performance bonus"],
    deadlineDays: 28,
  },
  {
    title: "Management Accountant",
    companySlug: "ncba-group",
    location: "Upper Hill, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 150000, showSalary: true,
    about: "NCBA Group is hiring a Management Accountant to support business decision-making through cost analysis, budgeting, and financial reporting. You will work closely with business unit heads to drive financial performance across the bank's operations.",
    requirements: ["CPA-K qualification", "3+ years in management accounting", "Bachelor's degree in Accounting or Finance", "Advanced Excel and data analysis skills", "Experience with cost accounting and variance analysis"],
    responsibilities: ["Prepare management reports and financial analysis", "Develop budgets and forecasts", "Perform variance analysis and recommend corrective actions", "Support strategic planning and decision-making", "Coordinate with external auditors"],
    highlights: ["Dynamic work environment", "Career development opportunities", "Health insurance for family", "Staff loan facilities", "Team-building and social events"],
    deadlineDays: 14,
  },
  {
    title: "Tax Consultant",
    companySlug: "pwc-kenya",
    location: "Westlands, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 120000, salaryMax: 180000, showSalary: true,
    about: "PwC Kenya's Tax Practice is looking for a Tax Consultant to advise multinational and local clients on tax planning, compliance, and controversy matters. You will work on cross-border tax issues, transfer pricing, and tax technology solutions.",
    requirements: ["CPA-K and Bachelor's degree in Tax/Accounting/Law", "3+ years in tax advisory or compliance", "Knowledge of Kenyan tax legislation and KRA procedures", "Experience with tax compliance software", "Strong analytical and research skills"],
    responsibilities: ["Prepare and review tax returns for clients", "Advise clients on tax planning strategies", "Handle tax audits and disputes with KRA", "Research and interpret tax legislation", "Contribute to tax publications and thought leadership"],
    highlights: ["Global PwC network and mobility", "Technical training and certifications", "Competitive compensation", "Health and wellness programs", "Flexible work arrangements"],
    deadlineDays: 21,
  },
  {
    title: "Accounts Payable Officer",
    companySlug: "britam-holdings",
    location: "Kenyatta Avenue, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 45000, salaryMax: 65000, showSalary: true,
    about: "Britam is seeking an Accounts Payable Officer to manage vendor payments, process invoices, and maintain accurate financial records. This is an excellent entry-level opportunity to build a career in insurance and financial services.",
    requirements: ["CPA Section 2 completed or in progress", "Diploma or degree in Accounting/Finance", "1+ year experience in accounts payable or general accounting", "Proficiency in ERP systems (SAP, Oracle)", "Attention to detail and strong organizational skills"],
    responsibilities: ["Process vendor invoices and payment requests", "Reconcile supplier statements", "Maintain accounts payable ledger", "Prepare payment schedules and forecasts", "Support month-end and year-end closing"],
    highlights: ["Stable company with growth opportunities", "Medical insurance", "Staff pension scheme", "Training and development programs", "Work-life balance"],
    deadlineDays: 10,
  },
  {
    title: "Financial Planning & Analysis Manager",
    companySlug: "absa-bank-kenya",
    location: "Westlands, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 200000, salaryMax: 280000, showSalary: true,
    about: "Absa Bank Kenya is looking for an FP&A Manager to lead the budgeting, forecasting, and strategic analysis function. You will be a key business partner to senior leadership, providing data-driven insights to support Absa's growth strategy in Kenya.",
    requirements: ["CPA-K, CFA, or MBA with Finance specialization", "7+ years in FP&A or strategic finance", "Advanced financial modeling and analytics skills", "Experience with BI tools (Power BI, Tableau)", "Leadership experience managing a small team"],
    responsibilities: ["Lead annual budgeting and quarterly reforecasting", "Develop financial models for strategic initiatives", "Prepare board and executive committee presentations", "Drive business partnering with department heads", "Implement FP&A best practices and tools"],
    highlights: ["Executive leadership exposure", "Absa Group international network", "Performance bonus and long-term incentives", "Comprehensive benefits package", "Career acceleration program"],
    deadlineDays: 28,
  },

  // ═══════════════════════════════════════
  // ENGINEERING (5 jobs)
  // ═══════════════════════════════════════
  {
    title: "Civil Engineer — Transmission Lines",
    companySlug: "kenya-power",
    location: "Parklands, Nairobi",
    category: "ENGINEERING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 160000, showSalary: true,
    about: "Kenya Power is seeking Civil Engineers to join its Transmission Infrastructure division. You will oversee the design and construction of electricity transmission line foundations, substations, and associated civil works across Kenya.",
    requirements: ["Bachelor's degree in Civil Engineering", "Registered with EBK (Engineers Board of Kenya)", "4+ years in civil/structural engineering", "Experience in power sector or heavy infrastructure projects", "Proficiency in AutoCAD and structural design software"],
    responsibilities: ["Design foundations for transmission line towers", "Supervise civil construction at substation sites", "Prepare bills of quantities and cost estimates", "Ensure compliance with engineering standards and safety", "Liaise with contractors and consultants"],
    highlights: ["Pension scheme and gratuity", "House allowance", "Medical insurance for family", "Job security in a critical national utility", "Ongoing professional development"],
    deadlineDays: 21,
  },
  {
    title: "Electrical Engineer — Power Distribution",
    companySlug: "kenya-power",
    location: "Mombasa",
    category: "ENGINEERING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 90000, salaryMax: 140000, showSalary: true,
    about: "Join Kenya Power's Coast Region team as an Electrical Engineer responsible for the design, planning, and maintenance of power distribution networks serving Mombasa and the surrounding coastal region.",
    requirements: ["Bachelor's degree in Electrical Engineering", "EBK registration", "3+ years in power distribution or transmission", "Knowledge of Kenyan electrical codes and standards", "Valid driving license"],
    responsibilities: ["Design and plan distribution network extensions", "Supervise maintenance and repair activities", "Conduct load analysis and network planning", "Prepare technical reports and drawings", "Coordinate with contractors on construction projects"],
    highlights: ["Regional posting with housing allowance", "Medical and life insurance", "Pension scheme", "Tool and transport allowance", "Training opportunities"],
    deadlineDays: 14,
  },
  {
    title: "Mechanical Engineer — Manufacturing",
    companySlug: "bata-shoe-kenya",
    location: "Industrial Area, Nairobi",
    category: "ENGINEERING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "Bata Shoe Company is looking for a Mechanical Engineer to maintain and optimize manufacturing equipment at its Limuru factory. You will ensure maximum uptime of production lines and drive continuous improvement initiatives.",
    requirements: ["Bachelor's degree in Mechanical Engineering or Mechatronics", "3+ years in manufacturing or industrial engineering", "Experience with preventive and predictive maintenance", "Knowledge of ISO quality management systems", "PLC programming skills are an advantage"],
    responsibilities: ["Maintain and repair manufacturing equipment", "Implement preventive maintenance schedules", "Drive continuous improvement and lean manufacturing", "Train maintenance technicians", "Manage spare parts inventory"],
    highlights: ["Stable manufacturing environment", "Medical insurance", "Transport allowance", "Staff shoe discount", "Career growth within Bata global network"],
    deadlineDays: 14,
  },
  {
    title: "Graduate Engineer — Renewable Energy",
    companySlug: "kenya-power",
    location: "Nakuru",
    category: "ENGINEERING",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 60000, salaryMax: 80000, showSalary: true,
    about: "Kenya Power's Graduate Engineer Program is a 2-year rotational program for fresh engineering graduates. You will gain exposure to geothermal, wind, solar, and hydro integration projects in Kenya's rapidly growing renewable energy sector.",
    requirements: ["Bachelor's degree in Electrical, Mechanical, or Energy Engineering", "Graduated in 2024 or 2025", "Strong academic performance (Second Class Upper or above)", "Registered with EBK (or pending)", "Willing to relocate within Kenya"],
    responsibilities: ["Rotate through different engineering departments", "Support renewable energy project implementation", "Assist in network planning and design", "Participate in on-the-job training programs", "Complete assigned projects and presentations"],
    highlights: ["Structured 2-year development program", "Dedicated mentorship", "Competitive graduate salary", "Pension and medical benefits", "Permanent placement upon successful completion"],
    deadlineDays: 7,
  },
  {
    title: "Process Engineer — Pharmaceutical Manufacturing",
    companySlug: "lupin-kenya",
    location: "Industrial Area, Nairobi",
    category: "ENGINEERING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 90000, salaryMax: 130000, showSalary: true,
    about: "Lupin Kenya is seeking a Process Engineer to optimize pharmaceutical manufacturing processes. You will work on process validation, efficiency improvements, and compliance with GMP (Good Manufacturing Practice) standards.",
    requirements: ["Bachelor's degree in Chemical, Pharmaceutical, or Industrial Engineering", "3+ years in pharmaceutical or process manufacturing", "Knowledge of GMP and WHO prequalification standards", "Experience with process optimization and Lean/Six Sigma", "Strong analytical and documentation skills"],
    responsibilities: ["Optimize pharmaceutical manufacturing processes", "Conduct process validation and qualification", "Implement continuous improvement initiatives", "Ensure compliance with GMP and regulatory standards", "Train production staff on standard procedures"],
    highlights: ["Pharmaceutical industry experience", "Medical insurance", "Annual bonus", "Training and development opportunities", "Global Lupin network"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // HEALTHCARE (4 jobs)
  // ═══════════════════════════════════════
  {
    title: "Registered Nurse — ICU",
    companySlug: "ministry-of-education-kenya",
    location: "Nairobi",
    category: "HEALTHCARE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 55000, salaryMax: 75000, showSalary: true,
    about: "The Ministry of Education is seeking experienced ICU Nurses for its medical facilities and staff clinics. You will provide critical care services, support occupational health programs, and contribute to staff wellness initiatives across government institutions.",
    requirements: ["Diploma or Degree in Nursing (KRCHN or BSc Nursing)", "Valid Nursing Council of Kenya license", "3+ years experience in critical care/ICU", "BLS and ACLS certification", "Strong clinical assessment and decision-making skills"],
    responsibilities: ["Provide intensive care nursing to patients", "Monitor and record patient vital signs and conditions", "Administer medications and treatments as prescribed", "Collaborate with multidisciplinary healthcare teams", "Maintain accurate patient records and documentation"],
    highlights: ["Government pension scheme", "Medical insurance", "Housing allowance", "Risk allowance", "Annual leave (30 days)"],
    deadlineDays: 14,
  },
  {
    title: "Pharmaceutical Sales Representative",
    companySlug: "lupin-kenya",
    location: "Kisumu",
    category: "HEALTHCARE",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 40000, salaryMax: 60000, showSalary: true,
    about: "Lupin Kenya is hiring a Pharmaceutical Sales Representative for its Western Kenya territory based in Kisumu. You will promote Lupin's pharmaceutical products to healthcare professionals, build relationships with hospitals and pharmacies, and achieve sales targets.",
    requirements: ["Diploma or Degree in Pharmacy, Nursing, or Biological Sciences", "Valid driving license", "1+ year experience in pharmaceutical sales (preferred)", "Excellent communication and relationship-building skills", "Knowledge of the Kisumu/Western Kenya healthcare market"],
    responsibilities: ["Promote pharmaceutical products to healthcare professionals", "Achieve monthly and quarterly sales targets", "Organize product presentations and medical education events", "Build and maintain relationships with key accounts", "Submit accurate sales reports and market feedback"],
    highlights: ["Company vehicle and fuel allowance", "Medical insurance", "Performance-based commission", "Training on pharmaceutical products", "Career growth in a global company"],
    deadlineDays: 10,
  },
  {
    title: "Medical Laboratory Technologist",
    companySlug: "lupin-kenya",
    location: "Industrial Area, Nairobi",
    category: "HEALTHCARE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 60000, salaryMax: 85000, showSalary: true,
    about: "Lupin Kenya's Quality Control laboratory is seeking a skilled Medical Laboratory Technologist. You will perform quality control testing on pharmaceutical products, ensure compliance with pharmacopoeial standards, and maintain laboratory accreditation.",
    requirements: ["Diploma or Degree in Medical Laboratory Sciences", "Registered with Kenya Medical Laboratory Technicians and Technologists Board", "3+ years experience in a QC laboratory", "Knowledge of pharmacopoeial methods (USP, BP, IP)", "Experience with HPLC, GC, and UV-Vis spectroscopy"],
    responsibilities: ["Perform quality control tests on raw materials and finished products", "Maintain and calibrate laboratory equipment", "Ensure compliance with GLP and GMP standards", "Prepare and review test reports", "Support stability studies and method validation"],
    highlights: ["Pharmaceutical QC experience", "Medical and dental insurance", "Training and certification support", "Annual performance bonus", "Job stability in essential manufacturing"],
    deadlineDays: 14,
  },
  {
    title: "Public Health Officer",
    companySlug: "unep-nairobi",
    location: "Gigiri, Nairobi",
    category: "HEALTHCARE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 120000, salaryMax: 170000, showSalary: true,
    about: "UNEP is recruiting a Public Health Officer to support its workplace health and safety programs at the Nairobi headquarters. You will coordinate health services, manage emergency response protocols, and implement staff wellness initiatives for over 1,000 international and local staff.",
    requirements: ["Master's degree in Public Health or related field", "3+ years in public health or occupational health", "Experience in UN or international organization settings preferred", "Knowledge of health emergency preparedness", "Strong coordination and communication skills"],
    responsibilities: ["Coordinate workplace health services", "Develop and implement health and safety protocols", "Manage staff wellness and mental health programs", "Respond to health emergencies", "Prepare health reports and risk assessments"],
    highlights: ["UN salary scale and benefits", "International work environment", "Pension fund (UN Joint Staff Pension Fund)", "30 days annual leave", "Education grant for dependents"],
    deadlineDays: 30,
  },

  // ═══════════════════════════════════════
  // EDUCATION (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "Lecturer — Computer Science",
    companySlug: "moringa-school",
    location: "Ngong Road, Nairobi",
    category: "EDUCATION",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "Moringa School is hiring a Computer Science Lecturer to deliver its flagship Software Engineering program. You will teach full-stack development, mentor students through projects, and continuously update curriculum to match industry needs.",
    requirements: ["Bachelor's degree in Computer Science or related field", "3+ years professional software development experience", "Teaching or mentoring experience preferred", "Strong knowledge of JavaScript, Python, and web technologies", "Passion for education and student success"],
    responsibilities: ["Deliver lectures and practical coding sessions", "Develop and update course curriculum", "Mentor students through capstone projects", "Grade assignments and provide constructive feedback", "Participate in industry partnerships and placements"],
    highlights: ["Mission-driven education environment", "Competitive salary and benefits", "Flexible work arrangements", "Professional development budget", "Impact on Kenya's tech talent pipeline"],
    deadlineDays: 14,
  },
  {
    title: "Curriculum Developer — Technical Training",
    companySlug: "moringa-school",
    location: "Ngong Road, Nairobi",
    category: "EDUCATION",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 90000, salaryMax: 130000, showSalary: true,
    about: "Moringa School is seeking a Curriculum Developer to design world-class technical training programs in Data Science, Software Engineering, and Cybersecurity. You will work with industry partners to ensure curriculum relevance and create engaging learning experiences.",
    requirements: ["Bachelor's degree in Education, Computer Science, or related field", "3+ years in curriculum development or instructional design", "Experience in EdTech or vocational training", "Knowledge of adult learning principles", "Project-based learning design experience"],
    responsibilities: ["Design and develop technical training curricula", "Collaborate with industry experts on content", "Create project-based learning experiences", "Review and update existing courses", "Conduct needs assessments and learner evaluations"],
    highlights: ["Impact-driven work", "Creative autonomy", "Learning and development budget", "Health insurance", "Flexible working hours"],
    deadlineDays: 21,
  },
  {
    title: "Education Program Officer",
    companySlug: "unep-nairobi",
    location: "Gigiri, Nairobi",
    category: "EDUCATION",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 110000, salaryMax: 160000, showSalary: true,
    about: "UNEP is recruiting an Education Program Officer to coordinate environmental education initiatives across Africa. You will work with governments, schools, and NGOs to integrate environmental education into national curricula and youth engagement programs.",
    requirements: ["Master's degree in Education, Environmental Studies, or related field", "4+ years in education program management", "Experience in environmental or sustainability education", "Strong project management and coordination skills", "Experience working with government agencies and NGOs"],
    responsibilities: ["Manage environmental education programs across Africa", "Coordinate with government education ministries", "Develop educational materials and resources", "Monitor and evaluate program impact", "Organize youth engagement events and workshops"],
    highlights: ["UN contract with competitive benefits", "International travel opportunities", "Pension fund participation", "Annual leave and home leave", "Multicultural work environment"],
    deadlineDays: 30,
  },

  // ═══════════════════════════════════════
  // MARKETING & COMMUNICATIONS (5 jobs)
  // ═══════════════════════════════════════
  {
    title: "Digital Marketing Manager",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 120000, salaryMax: 180000, showSalary: true,
    isFeatured: true,
    about: "Safaricom is seeking a Digital Marketing Manager to lead online marketing campaigns across M-Pesa, Data, and Voice products. You will manage digital channels, optimize customer acquisition funnels, and drive measurable ROI on digital spend.",
    requirements: ["Bachelor's degree in Marketing, Communications, or Business", "4+ years in digital marketing", "Experience with Google Ads, Facebook Ads, and programmatic advertising", "Proficiency in analytics tools (GA4, Google Tag Manager)", "Experience managing marketing budgets over KSh 50M annually"],
    responsibilities: ["Plan and execute digital marketing campaigns", "Manage paid search, social media, and display advertising", "Optimize conversion funnels and landing pages", "Analyze campaign performance and prepare reports", "Manage relationships with digital agencies"],
    highlights: ["Work on Kenya's most recognized brand", "Competitive salary and performance bonus", "Health insurance for family", "Flexible hybrid work", "M-Pesa staff benefits"],
    deadlineDays: 14,
  },
  {
    title: "Brand Manager — Insurance Products",
    companySlug: "britam-holdings",
    location: "Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 150000, showSalary: true,
    about: "Britam is looking for a Brand Manager to drive the brand strategy for its life insurance and general insurance products. You will develop brand positioning, manage above-the-line campaigns, and ensure consistent brand communication across all touchpoints.",
    requirements: ["Bachelor's degree in Marketing or related field", "4+ years in brand management or marketing communications", "Experience in financial services or insurance sector preferred", "Strong creative and strategic thinking abilities", "Experience managing external agencies and vendors"],
    responsibilities: ["Develop and execute brand strategy for insurance products", "Manage above-the-line and below-the-line campaigns", "Oversee creative development for marketing materials", "Conduct brand health tracking and market research", "Ensure brand consistency across all channels"],
    highlights: ["Leading insurance brand in East Africa", "Exposure to insurance and financial services", "Medical insurance and pension", "Performance-based bonus", "Career growth opportunities"],
    deadlineDays: 21,
  },
  {
    title: "Social Media & Content Specialist",
    companySlug: "twiga-foods",
    location: "Westlands, Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 50000, salaryMax: 70000, showSalary: true,
    about: "Twiga Foods is hiring a Social Media and Content Specialist to build its brand presence online. You will create engaging content for social media, manage community engagement, and support marketing campaigns for Kenya's leading agri-tech platform.",
    requirements: ["Bachelor's degree in Communications, Marketing, or related field", "1+ year experience in social media marketing or content creation", "Excellent writing and storytelling skills", "Proficiency with social media management tools", "Photography and video editing skills are a plus"],
    responsibilities: ["Create and publish content across social media platforms", "Engage with online community and respond to inquiries", "Support marketing campaigns with digital content", "Monitor social media trends and competitor activity", "Prepare monthly social media performance reports"],
    highlights: ["Fast-growing agri-tech startup", "Creative freedom and ownership", "Health insurance", "Transport allowance", "Opportunity to shape brand identity"],
    deadlineDays: 7,
  },
  {
    title: "Corporate Communications Manager",
    companySlug: "equity-bank-kenya",
    location: "Upper Hill, Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 180000, salaryMax: 250000, showSalary: true,
    about: "Equity Bank is seeking a Corporate Communications Manager to lead its internal and external communications strategy. You will manage media relations, corporate reputation, crisis communications, and stakeholder engagement across 11 countries.",
    requirements: ["Bachelor's degree in Communications, Public Relations, or Journalism", "7+ years in corporate communications or PR", "Experience in banking or financial services preferred", "Strong media relationships in Kenya and East Africa", "Crisis management experience"],
    responsibilities: ["Develop and implement corporate communications strategy", "Manage media relations and press coverage", "Handle crisis communications and issues management", "Oversee internal communications and staff engagement", "Coordinate stakeholder communications and events"],
    highlights: ["Regional role with East African exposure", "Executive leadership access", "Competitive compensation package", "Medical insurance for family", "International travel opportunities"],
    deadlineDays: 28,
  },
  {
    title: "Marketing Analytics Analyst",
    companySlug: "airtel-kenya",
    location: "Muthaiga, Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 55000, salaryMax: 80000, showSalary: true,
    about: "Airtel Kenya is looking for a Marketing Analytics Analyst to support data-driven marketing decisions. You will analyze customer data, campaign performance, and market trends to optimize Airtel's marketing strategies in the Kenyan market.",
    requirements: ["Bachelor's degree in Statistics, Mathematics, Marketing Analytics, or related", "1+ year experience in marketing analytics or data analysis", "Proficiency in SQL and Excel", "Experience with BI tools (Power BI, Tableau)", "Knowledge of digital marketing metrics"],
    responsibilities: ["Analyze marketing campaign performance", "Build dashboards and reports for marketing teams", "Segment customers for targeted campaigns", "Conduct market research and competitive analysis", "Support ROI measurement and attribution"],
    highlights: ["Telecom industry analytics experience", "Medical and life insurance", "Staff data and voice benefits", "Professional development opportunities", "Collaborative team environment"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // GOVERNMENT & PUBLIC SECTOR (4 jobs)
  // ═══════════════════════════════════════
  {
    title: "Finance Officer — Budget & Planning",
    companySlug: "kenya-revenue-authority",
    location: "Times Tower, Nairobi",
    category: "GOVERNMENT_PUBLIC_SECTOR",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "The Kenya Revenue Authority is recruiting a Finance Officer to join its Budget and Planning department. You will support budget preparation, expenditure monitoring, and financial reporting for KRA's nationwide operations.",
    requirements: ["CPA-K qualification", "Bachelor's degree in Finance, Accounting, or Economics", "3+ years in government finance or public financial management", "Knowledge of PFM Act and government budgeting processes", "Proficiency in IFMIS and financial reporting systems"],
    responsibilities: ["Prepare annual budget estimates and work plans", "Monitor budget execution and expenditure", "Prepare financial reports for management", "Coordinate with treasury and external auditors", "Support strategic planning and performance reporting"],
    highlights: ["Government pension scheme", "Medical insurance", "Housing allowance", "Risk allowance", "Job security and career progression"],
    deadlineDays: 21,
  },
  {
    title: "ICT Support Officer",
    companySlug: "ministry-of-education-kenya",
    location: "Nairobi",
    category: "GOVERNMENT_PUBLIC_SECTOR",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 40000, salaryMax: 55000, showSalary: true,
    about: "The Ministry of Education is seeking an ICT Support Officer to maintain IT systems, provide technical support to staff, and support digital transformation initiatives across the ministry's headquarters and county offices.",
    requirements: ["Diploma or Degree in IT, Computer Science, or related field", "CompTIA A+ or equivalent certification", "1+ year in IT support or systems administration", "Knowledge of Windows Server, Active Directory, and networking", "Good problem-solving and customer service skills"],
    responsibilities: ["Provide first-line and second-line IT support", "Maintain computer hardware and software", "Manage network infrastructure and user accounts", "Support digital transformation projects", "Maintain IT asset inventory and documentation"],
    highlights: ["Government pension scheme", "Medical insurance", "Leave allowance", "Training and development", "Job security in public service"],
    deadlineDays: 14,
  },
  {
    title: "Commissioner — Corporate Services",
    companySlug: "kenya-revenue-authority",
    location: "Times Tower, Nairobi",
    category: "GOVERNMENT_PUBLIC_SECTOR",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 250000, salaryMax: 350000, showSalary: true,
    isUrgent: true,
    about: "KRA is inviting applications from qualified Kenyans for the position of Commissioner, Corporate Services. This is a senior leadership role responsible for human resources, administration, procurement, and facilities management across KRA's nationwide operations.",
    requirements: ["Master's degree in Business Administration, Human Resources, or Public Administration", "10+ years in senior management in government or large organization", "Experience in public sector reform and transformation", "Knowledge of government procurement procedures", "Leadership and strategic management competencies"],
    responsibilities: ["Oversee human resources and administration", "Manage procurement and supply chain", "Lead organizational development and change management", "Develop and implement corporate policies", "Represent KRA in inter-agency committees"],
    highlights: ["Senior government appointment", "Competitive government salary", "Official vehicle and housing", "Medical insurance for family", "Government pension and gratuity"],
    deadlineDays: 14,
  },
  {
    title: "County Director of Education",
    companySlug: "ministry-of-education-kenya",
    location: "Kisumu",
    category: "GOVERNMENT_PUBLIC_SECTOR",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 130000, salaryMax: 180000, showSalary: true,
    about: "The Ministry of Education is seeking a County Director of Education for Kisumu County. You will oversee all educational institutions, coordinate curriculum implementation, manage education staff, and ensure quality standards across the county's primary, secondary, and tertiary institutions.",
    requirements: ["Master's degree in Education Administration or related field", "10+ years in education management", "Experience as a school principal or education officer", "Knowledge of CBC and Kenyan education policies", "Strong leadership and stakeholder management skills"],
    responsibilities: ["Oversee all educational institutions in the county", "Coordinate curriculum implementation and quality assurance", "Manage teaching and non-teaching staff", "Prepare budget estimates for county education", "Liaise with county government and stakeholders"],
    highlights: ["Senior government position", "House and transport allowance", "Medical insurance", "Government pension scheme", "Opportunity to impact education at county level"],
    deadlineDays: 21,
  },

  // ═══════════════════════════════════════
  // NGO & NONPROFIT (4 jobs)
  // ═══════════════════════════════════════
  {
    title: "Program Manager — Climate Change",
    companySlug: "unep-nairobi",
    location: "Gigiri, Nairobi",
    category: "NONPROFIT",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "CONTRACT",
    salaryMin: 200000, salaryMax: 300000, showSalary: true,
    isFeatured: true,
    about: "UNEP is recruiting a Program Manager for its Climate Change division to manage programs supporting African countries in implementing their Nationally Determined Contributions (NDCs). You will oversee a portfolio of climate adaptation and mitigation projects across the continent.",
    requirements: ["Master's degree in Environmental Science, Climate Change, or related field", "7+ years in environmental program management", "Experience with climate change policy and NDC implementation", "Strong project management and donor relations skills", "Experience working with African governments and UN agencies"],
    responsibilities: ["Manage climate change programs across Africa", "Coordinate with government counterparts and partners", "Prepare program proposals and donor reports", "Monitor project implementation and evaluate outcomes", "Represent UNEP at international climate events"],
    highlights: ["UN international professional salary", "Pension fund participation", "30 days annual leave + home leave", "Education grant for dependents", "International travel and networking"],
    deadlineDays: 30,
  },
  {
    title: "Monitoring & Evaluation Specialist",
    companySlug: "unep-nairobi",
    location: "Gigiri, Nairobi",
    category: "NONPROFIT",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 130000, salaryMax: 180000, showSalary: true,
    about: "UNEP seeks an M&E Specialist to design and implement monitoring and evaluation frameworks for its environmental programs. You will develop data collection tools, conduct evaluations, and produce evidence-based reports to inform program decision-making.",
    requirements: ["Master's degree in Statistics, Evaluation, or related field", "4+ years in M&E for development programs", "Experience with logical frameworks and theory of change", "Proficiency in data analysis tools (SPSS, STATA, or R)", "Strong report writing and presentation skills"],
    responsibilities: ["Design M&E frameworks for environmental programs", "Develop data collection tools and methodologies", "Conduct baseline, mid-term, and endline evaluations", "Train program staff on M&E practices", "Produce evaluation reports and recommendations"],
    highlights: ["UN contract terms", "Multicultural team environment", "Pension fund and medical insurance", "Professional development opportunities", "Meaningful environmental impact work"],
    deadlineDays: 30,
  },
  {
    title: "Grants & Partnerships Manager",
    companySlug: "unep-nairobi",
    location: "Gigiri, Nairobi",
    category: "NONPROFIT",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 140000, salaryMax: 190000, showSalary: true,
    about: "UNEP is looking for a Grants and Partnerships Manager to manage relationships with bilateral and multilateral donors, coordinate funding proposals, and ensure compliance with donor requirements across a portfolio of environmental programs.",
    requirements: ["Master's degree in International Development, Business, or related field", "5+ years in grants management or partnerships", "Experience with major donors (EU, USAID, GEF, Green Climate Fund)", "Knowledge of UN financial rules and regulations", "Strong negotiation and relationship management skills"],
    responsibilities: ["Manage donor relationships and communications", "Coordinate proposal development and fundraising", "Ensure donor compliance and reporting", "Monitor grant expenditure and budget utilization", "Facilitate partnership building with governments and NGOs"],
    highlights: ["Senior UN role", "Global network and exposure", "Competitive UN benefits package", "Professional growth and learning", "Contribution to global environmental goals"],
    deadlineDays: 30,
  },
  {
    title: "Field Coordinator — Community Development",
    companySlug: "twiga-foods",
    location: "Nakuru",
    category: "NONPROFIT",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 70000, salaryMax: 95000, showSalary: true,
    about: "Twiga Foods' social impact arm is seeking a Field Coordinator to manage farmer training and community development programs in Nakuru and surrounding counties. You will work directly with smallholder farmers to improve agricultural practices and market access.",
    requirements: ["Bachelor's degree in Agriculture, Community Development, or related field", "3+ years in community development or agricultural extension", "Experience working with smallholder farmers", "Strong community mobilization skills", "Valid motorcycle riding license"],
    responsibilities: ["Coordinate farmer training programs", "Mobilize and organize farmer groups", "Monitor program implementation and outcomes", "Prepare field reports and documentation", "Liaise with local government and partners"],
    highlights: ["Community impact work", "Transport and field allowances", "Medical insurance", "Professional development", "Growing social enterprise"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // HUMAN RESOURCES (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "HR Business Partner",
    companySlug: "kcb-group",
    location: "Kenyatta Avenue, Nairobi",
    category: "HUMAN_RESOURCES",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 150000, salaryMax: 220000, showSalary: true,
    about: "KCB Group is looking for an HR Business Partner to support its Retail Banking division. You will partner with business leaders to drive people strategies, manage talent, and create an engaging work environment across KCB's largest business unit.",
    requirements: ["Bachelor's degree in Human Resources, Psychology, or Business", "HR professional certification (CHRP or CIPD)", "6+ years in HR business partnering or generalist roles", "Experience in banking or financial services preferred", "Strong understanding of Kenyan labour law"],
    responsibilities: ["Partner with business leaders on people strategies", "Manage recruitment and onboarding for the division", "Drive performance management and talent development", "Handle employee relations and disciplinary matters", "Support organizational change and transformation"],
    highlights: ["Strategic HR leadership role", "Regional bank exposure", "Performance bonus", "Medical insurance for family", "Career progression to HR Director"],
    deadlineDays: 21,
  },
  {
    title: "Recruitment Specialist",
    companySlug: "andela-kenya",
    location: "Pinewood Place, Nairobi",
    category: "HUMAN_RESOURCES",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "Andela is seeking a Recruitment Specialist to manage the end-to-end recruitment process for its engineering and non-engineering roles in Kenya. You will identify, attract, and hire top talent in a competitive tech market.",
    requirements: ["Bachelor's degree in HR, Psychology, or related field", "3+ years in technical recruitment or talent acquisition", "Experience recruiting software engineers and tech roles", "Familiarity with applicant tracking systems (Greenhouse, Lever)", "Strong sourcing skills (LinkedIn, GitHub, communities)"],
    responsibilities: ["Manage end-to-end recruitment for assigned roles", "Source and screen candidates through various channels", "Conduct initial interviews and coordinate technical assessments", "Manage offer processes and candidate experience", "Track recruitment metrics and report on pipeline"],
    highlights: ["Tech industry recruitment experience", "Global company culture", "Competitive salary", "Remote work flexibility", "Professional development"],
    deadlineDays: 14,
  },
  {
    title: "Learning & Development Coordinator",
    companySlug: "equity-bank-kenya",
    location: "Upper Hill, Nairobi",
    category: "HUMAN_RESOURCES",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 55000, salaryMax: 75000, showSalary: true,
    about: "Equity Bank's Learning and Development team is hiring a Coordinator to support training programs across the bank's 190+ branches. You will coordinate logistics, manage the Learning Management System, and support curriculum delivery.",
    requirements: ["Bachelor's degree in HR, Education, or related field", "1+ year in training coordination or L&D support", "Proficiency with LMS platforms", "Strong organizational and multitasking skills", "Knowledge of instructional design basics"],
    responsibilities: ["Coordinate training logistics and schedules", "Manage the Learning Management System", "Support curriculum development and content creation", "Track training attendance and completion", "Prepare training reports and evaluations"],
    highlights: ["Largest bank in East Africa", "Structured career development", "Medical insurance", "Training opportunities", "Collaborative team"],
    deadlineDays: 10,
  },

  // ═══════════════════════════════════════
  // CREATIVE & DESIGN (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "UI/UX Designer",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "CREATIVE_DESIGN",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 160000, showSalary: true,
    about: "Safaricom is looking for a talented UI/UX Designer to join its Digital Experience team. You will design user interfaces for the MySafaricom App, M-Pesa Business tools, and web platforms serving millions of Kenyan customers.",
    requirements: ["Bachelor's degree in Design, HCI, or related field", "3+ years in UI/UX design for mobile and web", "Proficiency in Figma and design systems", "Portfolio showcasing mobile app and web design projects", "Understanding of accessibility standards and user research"],
    responsibilities: ["Design intuitive user interfaces for mobile and web", "Conduct user research and usability testing", "Create wireframes, prototypes, and design specifications", "Collaborate with product managers and developers", "Maintain and evolve the Safaricom design system"],
    highlights: ["Design for millions of users", "Impact on Kenya's digital transformation", "Health insurance for family", "Flexible hybrid work", "Design tools and conference budget"],
    deadlineDays: 14,
  },
  {
    title: "Graphic Designer — Brand & Marketing",
    companySlug: "ncba-group",
    location: "Upper Hill, Nairobi",
    category: "CREATIVE_DESIGN",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 45000, salaryMax: 65000, showSalary: true,
    about: "NCBA Group is seeking a Graphic Designer to create visual content for marketing campaigns, social media, branch signage, and internal communications. You will support the brand team in maintaining NCBA's visual identity across all touchpoints.",
    requirements: ["Diploma or Degree in Graphic Design, Fine Arts, or related", "1+ year experience in graphic design", "Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)", "Strong portfolio of brand and marketing design work", "Knowledge of print and digital design standards"],
    responsibilities: ["Create marketing collaterals and campaign visuals", "Design social media graphics and digital ads", "Develop branch signage and POS materials", "Support event branding and internal communications", "Maintain brand guidelines consistency"],
    highlights: ["Banking sector design experience", "Medical insurance", "Training and development", "Team-oriented work environment", "Career growth in corporate design"],
    deadlineDays: 7,
  },
  {
    title: "Motion Graphics Designer",
    companySlug: "airtel-kenya",
    location: "Muthaiga, Nairobi",
    category: "CREATIVE_DESIGN",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    salaryMin: 70000, salaryMax: 110000, showSalary: true,
    about: "Airtel Kenya is looking for a Motion Graphics Designer to create compelling video content for TV commercials, social media, and digital campaigns. You will bring Airtel's brand stories to life through animation, visual effects, and dynamic content.",
    requirements: ["Diploma or Degree in Animation, Film, or Design", "2+ years in motion graphics or video production", "Proficiency in After Effects, Premiere Pro, and Cinema 4D", "Strong portfolio of motion graphics work", "Understanding of storytelling and brand communication"],
    responsibilities: ["Create motion graphics for TV and digital campaigns", "Animate logos, text, and visual elements", "Edit video content for social media", "Collaborate with creative team on campaign concepts", "Manage project timelines and deliverables"],
    highlights: ["Creative freedom in telecom marketing", "Medical and life insurance", "Staff data benefits", "Modern studio setup", "Portfolio-building opportunities"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // LEGAL & COMPLIANCE (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "Legal Counsel — Corporate & Commercial",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "LEGAL",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 200000, salaryMax: 300000, showSalary: true,
    about: "Safaricom is recruiting an experienced Legal Counsel to join its in-house legal team. You will provide legal advice on commercial contracts, regulatory compliance, M&A transactions, and corporate governance matters for Kenya's largest listed company.",
    requirements: ["Bachelor's degree in Law (LLB)", "Advocate of the High Court of Kenya with a valid practicing certificate", "5+ years post-admission experience in corporate/commercial law", "Experience in telecommunications or technology law is an advantage", "Strong drafting, negotiation, and analytical skills"],
    responsibilities: ["Draft and review commercial contracts and agreements", "Advise on regulatory compliance and licensing", "Support M&A and investment transactions", "Manage litigation and dispute resolution", "Provide legal training to business teams"],
    highlights: ["In-house counsel at Kenya's top company", "Complex and impactful legal work", "Competitive executive compensation", "Health insurance for family", "Professional development and CLE sponsorship"],
    deadlineDays: 21,
  },
  {
    title: "Compliance Officer — Banking",
    companySlug: "cooperative-bank-kenya",
    location: "Haile Selassie Avenue, Nairobi",
    category: "LEGAL",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 150000, showSalary: true,
    about: "Co-operative Bank is seeking a Compliance Officer to ensure adherence to CBK guidelines, AML/CFT regulations, and internal policies. You will conduct compliance monitoring, prepare regulatory reports, and support the implementation of compliance programs.",
    requirements: ["Bachelor's degree in Law, Finance, or related field", "3+ years in banking compliance or regulatory affairs", "Knowledge of CBK prudential guidelines and AML/CFT laws", "Professional certification (ACAMS or CAMS) is an advantage", "Strong analytical and report writing skills"],
    responsibilities: ["Monitor compliance with regulatory requirements", "Prepare CBK and other regulatory returns", "Conduct compliance risk assessments", "Investigate and report suspicious transactions", "Train staff on compliance policies and procedures"],
    highlights: ["Banking compliance career path", "Medical insurance", "Pension scheme", "Staff banking facilities", "Professional development support"],
    deadlineDays: 14,
  },
  {
    title: "Company Secretary",
    companySlug: "britam-holdings",
    location: "Nairobi",
    category: "LEGAL",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 180000, salaryMax: 250000, showSalary: true,
    about: "Britam Holdings is seeking a Company Secretary to manage corporate governance, board administration, and regulatory compliance for this listed financial services group with operations in five African countries.",
    requirements: ["Bachelor's degree in Law (LLB)", "Advocate of the High Court of Kenya", "Certified Company Secretary (ICPSK or equivalent)", "5+ years as a Company Secretary in a listed company", "Strong knowledge of corporate governance and CMA regulations"],
    responsibilities: ["Manage board meetings and corporate governance", "Ensure regulatory compliance with CMA and IRA", "Maintain statutory registers and filings", "Advise the board on governance matters", "Coordinate with external legal counsel"],
    highlights: ["Listed company governance role", "Regional exposure", "Executive compensation", "Medical insurance and pension", "Board-level interaction"],
    deadlineDays: 21,
  },

  // ═══════════════════════════════════════
  // LOGISTICS & SUPPLY CHAIN (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "Supply Chain Manager",
    companySlug: "twiga-foods",
    location: "Westlands, Nairobi",
    category: "SUPPLY_CHAIN",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 150000, salaryMax: 220000, showSalary: true,
    about: "Twiga Foods is looking for a Supply Chain Manager to optimize its food distribution network connecting farmers to urban vendors. You will manage logistics operations across Kenya, reduce food waste, and improve delivery efficiency using technology and data.",
    requirements: ["Bachelor's degree in Supply Chain, Logistics, or Business", "5+ years in supply chain or logistics management", "Experience in FMCG, agriculture, or food distribution", "Strong analytical and data-driven decision-making skills", "Knowledge of cold chain logistics is an advantage"],
    responsibilities: ["Manage end-to-end supply chain operations", "Optimize distribution routes and delivery schedules", "Oversee warehouse management and inventory control", "Negotiate with logistics service providers", "Implement supply chain technology solutions"],
    highlights: ["Mission-driven agri-tech company", "Competitive salary and benefits", "Medical insurance", "Stock options in a growing startup", "Impact on food security"],
    deadlineDays: 21,
  },
  {
    title: "Procurement Officer",
    companySlug: "kenya-power",
    location: "Parklands, Nairobi",
    category: "SUPPLY_CHAIN",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "Kenya Power is seeking a Procurement Officer to manage the sourcing and procurement of materials, equipment, and services for its electricity transmission and distribution operations. You will ensure value for money and compliance with public procurement procedures.",
    requirements: ["Bachelor's degree in Supply Chain, Procurement, or Business", "CIPS qualification or equivalent", "3+ years in procurement in a large organization", "Knowledge of Public Procurement and Asset Disposal Act", "Experience with ERP procurement modules"],
    responsibilities: ["Manage procurement processes for materials and services", "Prepare tender documents and evaluate bids", "Negotiate contracts with suppliers", "Maintain supplier relationships and performance monitoring", "Ensure compliance with procurement regulations"],
    highlights: ["Government parastatal benefits", "Pension scheme", "Medical insurance", "Training and development", "Job security"],
    deadlineDays: 14,
  },
  {
    title: "Warehouse Supervisor",
    companySlug: "bata-shoe-kenya",
    location: "Limuru",
    category: "SUPPLY_CHAIN",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 45000, salaryMax: 65000, showSalary: true,
    about: "Bata Kenya is looking for a Warehouse Supervisor to manage its Limuru distribution warehouse. You will oversee receiving, storage, picking, and dispatch of footwear products, ensuring accuracy and efficiency in inventory management.",
    requirements: ["Diploma or Degree in Supply Chain, Logistics, or related", "3+ years in warehouse management or inventory control", "Experience with warehouse management systems (WMS)", "Strong leadership and team management skills", "Knowledge of health and safety standards"],
    responsibilities: ["Supervise daily warehouse operations", "Manage inventory accuracy and stock control", "Coordinate picking, packing, and dispatch", "Train and manage warehouse staff", "Prepare inventory reports and cycle counts"],
    highlights: ["Manufacturing and retail experience", "Medical insurance", "Transport and housing allowance", "Staff discount", "Career growth opportunities"],
    deadlineDays: 10,
  },

  // ═══════════════════════════════════════
  // CUSTOMER SERVICE (4 jobs)
  // ═══════════════════════════════════════
  {
    title: "Customer Experience Team Lead",
    companySlug: "safaricom-plc",
    location: "Westlands, Nairobi",
    category: "CUSTOMER_SERVICE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 80000, salaryMax: 120000, showSalary: true,
    about: "Safaricom is seeking a Customer Experience Team Lead to manage a team of 15 customer service advisors handling M-Pesa, Data, and Voice inquiries. You will drive customer satisfaction, handle escalations, and implement process improvements.",
    requirements: ["Bachelor's degree in Business, Communications, or related", "3+ years in customer service management", "Experience in telecommunications or banking", "Strong leadership and people management skills", "Knowledge of CRM systems (Salesforce, Zendesk)"],
    responsibilities: ["Lead a team of customer service advisors", "Handle complex customer escalations", "Monitor team performance metrics (CSAT, AHT, FCR)", "Coach and develop team members", "Identify and implement process improvements"],
    highlights: ["Leadership role at Kenya's top company", "Performance-based bonus", "Health insurance", "Flexible work schedule", "Career progression to management"],
    deadlineDays: 14,
  },
  {
    title: "Customer Support Representative",
    companySlug: "airtel-kenya",
    location: "Nairobi",
    category: "CUSTOMER_SERVICE",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 30000, salaryMax: 45000, showSalary: true,
    about: "Airtel Kenya is hiring Customer Support Representatives for its call center in Nairobi. You will handle inbound calls, resolve customer queries about mobile services, and ensure a positive customer experience for Airtel subscribers.",
    requirements: ["Diploma or Degree in any field", "Excellent communication skills in English and Kiswahili", "6+ months customer service experience (preferred)", "Basic computer literacy", "Ability to work in shifts"],
    responsibilities: ["Handle inbound customer calls and inquiries", "Resolve billing, network, and service issues", "Update customer records in CRM system", "Upsell products and services where appropriate", "Meet daily call handling targets"],
    highlights: ["Entry-level opportunity in telecom", "Medical insurance", "Staff data and voice benefits", "Training provided", "Career growth within Airtel"],
    deadlineDays: 7,
  },
  {
    title: "Client Relationship Manager",
    companySlug: "kcb-group",
    location: "Nairobi",
    category: "CUSTOMER_SERVICE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 100000, salaryMax: 150000, showSalary: true,
    about: "KCB Group is looking for a Client Relationship Manager to manage high-value banking relationships and ensure customer satisfaction for premium clients. You will proactively engage clients, cross-sell bank products, and resolve complex service issues.",
    requirements: ["Bachelor's degree in Business, Finance, or related", "3+ years in relationship management or account management", "Experience in banking or financial services", "Strong interpersonal and negotiation skills", "Knowledge of banking products and services"],
    responsibilities: ["Manage and grow client relationships", "Proactively identify client needs and cross-sell products", "Resolve complex service issues and escalations", "Prepare client reviews and financial needs analyses", "Achieve customer satisfaction and revenue targets"],
    highlights: ["Premium banking experience", "Performance-based incentive", "Medical insurance", "Career growth in banking", "Professional development"],
    deadlineDays: 14,
  },
  {
    title: "Customer Success Manager — B2B",
    companySlug: "twiga-foods",
    location: "Westlands, Nairobi",
    category: "CUSTOMER_SERVICE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 75000, salaryMax: 110000, showSalary: true,
    about: "Twiga Foods is seeking a Customer Success Manager to manage relationships with its B2B clients including restaurants, hotels, and retail vendors. You will ensure customer satisfaction, drive adoption of Twiga's platform, and identify upselling opportunities.",
    requirements: ["Bachelor's degree in Business, Marketing, or related", "2+ years in customer success, account management, or B2B sales", "Experience in FMCG, food, or agri-tech sectors preferred", "Strong relationship-building and problem-solving skills", "Data-driven approach to customer management"],
    responsibilities: ["Manage B2B customer relationships", "Drive platform adoption and engagement", "Handle customer onboarding and training", "Identify upselling and cross-selling opportunities", "Track customer health metrics and churn risk"],
    highlights: ["Growing agri-tech startup", "Customer-facing role with business impact", "Medical insurance", "Performance-based bonus", "Opportunity to shape customer success function"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // CONSULTING (3 jobs)
  // ═══════════════════════════════════════
  {
    title: "Management Consultant — Strategy",
    companySlug: "pwc-kenya",
    location: "Westlands, Nairobi",
    category: "CONSULTING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 150000, salaryMax: 220000, showSalary: true,
    isFeatured: true,
    about: "PwC Kenya's Strategy Consulting practice is hiring Consultants to work on transformation projects for leading organizations in East Africa. You will conduct market research, develop strategic recommendations, and support implementation for clients across financial services, technology, and public sector.",
    requirements: ["MBA or Master's degree from a recognized university", "3+ years in management consulting or strategy", "Strong analytical and problem-solving skills", "Excellent presentation and communication abilities", "Experience in financial services, telecom, or public sector"],
    responsibilities: ["Conduct research and analysis for strategy projects", "Develop strategic recommendations and business cases", "Prepare client presentations and reports", "Support project management and delivery", "Build relationships with client stakeholders"],
    highlights: ["Big Four consulting experience", "Global PwC network", "Structured career progression", "Competitive compensation", "International mobility opportunities"],
    deadlineDays: 21,
  },
  {
    title: "IT Consultant — Digital Transformation",
    companySlug: "kpmg-east-africa",
    location: "Upper Hill, Nairobi",
    category: "CONSULTING",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "PERMANENT",
    salaryMin: 130000, salaryMax: 190000, showSalary: true,
    about: "KPMG East Africa's Technology Consulting practice is seeking IT Consultants to help clients navigate digital transformation. You will assess technology landscapes, recommend solutions, and support implementation of ERP, cloud, and data analytics projects.",
    requirements: ["Bachelor's degree in IT, Computer Science, or related", "3+ years in IT consulting or technology implementation", "Experience with ERP systems (SAP, Oracle, Dynamics)", "Knowledge of cloud computing (AWS, Azure, Google Cloud)", "Strong project management skills"],
    responsibilities: ["Assess client technology landscapes", "Develop digital transformation roadmaps", "Support ERP and cloud implementation projects", "Prepare proposals and client deliverables", "Manage project workstreams and client relationships"],
    highlights: ["Big Four IT consulting", "Exposure to leading technologies", "Training and certification support", "Health and wellness programs", "Career development framework"],
    deadlineDays: 21,
  },
  {
    title: "Associate Consultant — Risk Advisory",
    companySlug: "pwc-kenya",
    location: "Westlands, Nairobi",
    category: "CONSULTING",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 90000, salaryMax: 130000, showSalary: true,
    about: "PwC Kenya's Risk Advisory practice is hiring Associate Consultants to support internal audit, enterprise risk management, and compliance projects for clients across East Africa. This is an excellent entry point into a consulting career at a Big Four firm.",
    requirements: ["Bachelor's degree in Accounting, Finance, IT, or related field", "CPA-K, CIA, or CISA certification (or in progress)", "Strong analytical and critical thinking skills", "Excellent written and verbal communication", "Willingness to travel for client engagements"],
    responsibilities: ["Support internal audit engagements", "Conduct risk assessments and control testing", "Prepare audit working papers and reports", "Assist in compliance reviews", "Contribute to business development efforts"],
    highlights: ["Big Four career launch", "Structured learning and development", "Certification sponsorship", "Diverse client exposure", "Mentorship from senior consultants"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // REMOTE JOBS (cross-category, flagged)
  // ═══════════════════════════════════════
  {
    title: "Technical Writer — API Documentation",
    companySlug: "andela-kenya",
    location: "Remote — Kenya",
    category: "TECHNOLOGY",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    isRemote: true,
    salaryMin: 80000, salaryMax: 130000, showSalary: true,
    about: "Andela is looking for a Technical Writer to create and maintain API documentation, developer guides, and SDK tutorials. You will work with engineering teams across multiple time zones to produce clear, accurate, and comprehensive documentation.",
    requirements: ["2+ years in technical writing or documentation", "Strong writing and editing skills", "Experience with API documentation (REST, GraphQL)", "Familiarity with documentation tools (GitBook, ReadMe, Docusaurus)", "Basic understanding of software development"],
    responsibilities: ["Write and maintain API documentation", "Create developer guides and tutorials", "Review and edit technical content", "Collaborate with engineers on documentation accuracy", "Manage documentation versioning and updates"],
    highlights: ["Fully remote position", "Flexible hours", "Internet and equipment stipend", "Learning and development budget", "Global team collaboration"],
    deadlineDays: 21,
  },
  {
    title: "Content Marketing Writer",
    companySlug: "moringa-school",
    location: "Remote — Kenya",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "PART_TIME",
    experienceLevel: "MID",
    employmentType: "CONTRACT",
    isRemote: true,
    salaryMin: 40000, salaryMax: 60000, showSalary: true,
    about: "Moringa School is hiring a part-time Content Writer to produce blog posts, case studies, and social media content about tech careers in Africa. You will help position Moringa as the leading thought leader in African tech education.",
    requirements: ["2+ years in content writing or copywriting", "Strong portfolio of published articles", "Knowledge of the African tech ecosystem", "Excellent research and storytelling skills", "SEO writing knowledge is a plus"],
    responsibilities: ["Write blog posts and articles about tech careers", "Create case studies featuring Moringa alumni", "Develop social media content and newsletters", "Conduct interviews with industry professionals", "Optimize content for SEO"],
    highlights: ["Remote and flexible schedule", "Part-time (20 hours/week)", "Per-article payment model", "Byline credit", "Exposure to tech industry leaders"],
    deadlineDays: 14,
  },

  // ═══════════════════════════════════════
  // PART-TIME JOBS
  // ═══════════════════════════════════════
  {
    title: "Data Entry Clerk",
    companySlug: "cooperative-bank-kenya",
    location: "Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "PART_TIME",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    salaryMin: 20000, salaryMax: 30000, showSalary: true,
    about: "Co-operative Bank is hiring part-time Data Entry Clerks to support its digital transformation project. You will digitize paper records, verify data accuracy, and enter customer information into the bank's core banking system.",
    requirements: ["Diploma or Certificate in IT, Business, or related field", "Typing speed of 40+ WPM with accuracy", "Basic computer literacy (MS Office)", "Attention to detail", "Available for morning or afternoon shifts"],
    responsibilities: ["Digitize paper customer records", "Enter and verify data in banking systems", "Maintain data quality and accuracy", "Report discrepancies and errors", "Meet daily data entry targets"],
    highlights: ["Flexible part-time hours", "Banking environment exposure", "Transport allowance", "Certificate of service", "Potential for full-time conversion"],
    deadlineDays: 7,
  },
  {
    title: "Social Media Moderator",
    companySlug: "safaricom-plc",
    location: "Nairobi",
    category: "CUSTOMER_SERVICE",
    jobType: "PART_TIME",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    salaryMin: 25000, salaryMax: 35000, showSalary: true,
    about: "Safaricom is looking for part-time Social Media Moderators to manage customer inquiries and feedback across social media platforms (Twitter, Facebook, Instagram). You will respond to customer queries, escalate issues, and maintain brand tone.",
    requirements: ["Diploma or Degree in Communications, Marketing, or related", "Excellent written communication in English and Kiswahili", "Active social media user with understanding of platform dynamics", "Customer service orientation", "Available for evening and weekend shifts"],
    responsibilities: ["Monitor and respond to social media inquiries", "Escalate complex issues to relevant teams", "Maintain brand tone and communication standards", "Track and report social media metrics", "Flag emerging customer issues and trends"],
    highlights: ["Part-time flexible hours", "Work for Kenya's top brand", "Social media management experience", "Training provided", "Staff data benefits"],
    deadlineDays: 7,
  },

  // ═══════════════════════════════════════
  // INTERNSHIPS
  // ═══════════════════════════════════════
  {
    title: "Finance Intern",
    companySlug: "kpmg-east-africa",
    location: "Upper Hill, Nairobi",
    category: "FINANCE_ACCOUNTING",
    jobType: "INTERNSHIP",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    about: "KPMG East Africa offers a 3-month Finance Internship for university students pursuing accounting or finance degrees. You will gain hands-on experience in audit procedures, financial analysis, and professional services.",
    requirements: ["Currently pursuing a degree in Accounting, Finance, or related", "CPA Section 2 completed", "Strong academic record", "Proficiency in Microsoft Excel", "Strong analytical skills"],
    responsibilities: ["Assist with audit fieldwork", "Prepare financial analysis spreadsheets", "Support client document review", "Attend team meetings and training sessions", "Complete assigned learning modules"],
    highlights: ["Big Four internship experience", "Monthly stipend", "Mentorship from managers", "Certificate upon completion", "Potential for graduate recruitment"],
    deadlineDays: 7,
  },
  {
    title: "Marketing Intern",
    companySlug: "britam-holdings",
    location: "Nairobi",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "INTERNSHIP",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    about: "Britam is offering a 3-month Marketing Internship for creative and ambitious students. You will support marketing campaigns, create content, and gain exposure to insurance marketing in East Africa's leading insurance group.",
    requirements: ["Currently pursuing a degree in Marketing, Communications, or Business", "Creative portfolio or writing samples", "Proficiency in social media platforms", "Strong communication skills", "Available for 3 months full-time"],
    responsibilities: ["Assist with marketing campaign execution", "Create social media content", "Support event planning and coordination", "Conduct market research", "Prepare marketing reports"],
    highlights: ["Insurance industry exposure", "Monthly stipend of KSh 20,000", "Mentorship and coaching", "Networking opportunities", "Certificate upon completion"],
    deadlineDays: 7,
  },
  {
    title: "Human Resources Intern",
    companySlug: "equity-bank-kenya",
    location: "Upper Hill, Nairobi",
    category: "HUMAN_RESOURCES",
    jobType: "INTERNSHIP",
    experienceLevel: "ENTRY",
    employmentType: "TEMPORARY",
    about: "Equity Bank's HR department is offering a 3-month internship for students interested in building a career in human resources. You will support recruitment, training coordination, employee engagement, and HR administration.",
    requirements: ["Currently pursuing a degree in HR, Psychology, or Business", "Strong interpersonal skills", "Proficiency in Microsoft Office", "Attention to detail and confidentiality", "Available for 3 months full-time"],
    responsibilities: ["Support recruitment screening and scheduling", "Coordinate training sessions and logistics", "Assist with employee onboarding", "Maintain HR records and documentation", "Support employee engagement activities"],
    highlights: ["East Africa's largest bank", "Monthly stipend", "HR mentorship", "Exposure to banking HR operations", "Certificate upon completion"],
    deadlineDays: 7,
  },

  // ═══════════════════════════════════════
  // LOCATION-SPECIFIC JOBS (Mombasa, Kisumu, Nakuru)
  // ═══════════════════════════════════════
  {
    title: "Hotel Manager",
    companySlug: "unep-nairobi",
    location: "Mombasa",
    category: "MARKETING_COMMUNICATIONS",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 120000, salaryMax: 180000, showSalary: true,
    about: "A leading hotel group in Mombasa is seeking an experienced Hotel Manager to oversee daily operations, guest services, and revenue management. You will lead a team of 80+ staff and ensure exceptional guest experiences at this beachfront property.",
    requirements: ["Bachelor's degree in Hospitality Management or Business", "7+ years in hotel management", "Experience in 4- or 5-star hotel operations", "Strong leadership and team management skills", "Knowledge of hotel management systems (Opera, Fidelio)"],
    responsibilities: ["Oversee all hotel operations", "Manage guest services and satisfaction", "Drive revenue and occupancy targets", "Lead and develop hotel staff", "Ensure compliance with health and safety standards"],
    highlights: ["Beachfront property management", "Accommodation and meals provided", "Performance-based bonus", "Medical insurance", "Tourism industry career"],
    deadlineDays: 21,
  },
  {
    title: "Logistics Coordinator — Port Operations",
    companySlug: "twiga-foods",
    location: "Mombasa",
    category: "SUPPLY_CHAIN",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 40000, salaryMax: 55000, showSalary: true,
    about: "Twiga Foods is hiring a Logistics Coordinator for its Mombasa operations. You will coordinate shipments from the port of Mombasa, manage customs documentation, and ensure timely delivery of goods to warehouses and distribution centers.",
    requirements: ["Diploma or Degree in Logistics, Supply Chain, or related", "1+ year in logistics or shipping operations", "Knowledge of customs clearance procedures", "Strong organizational skills", "Valid driving license"],
    responsibilities: ["Coordinate port shipments and deliveries", "Manage customs documentation", "Track shipments and update logistics systems", "Communicate with transporters and suppliers", "Prepare shipping and delivery reports"],
    highlights: ["Port operations experience", "Medical insurance", "Transport allowance", "Career growth in logistics", "Coastal lifestyle"],
    deadlineDays: 10,
  },
  {
    title: "Branch Manager — Retail Banking",
    companySlug: "kcb-group",
    location: "Kisumu",
    category: "FINANCE_ACCOUNTING",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    employmentType: "PERMANENT",
    salaryMin: 130000, salaryMax: 180000, showSalary: true,
    about: "KCB Group is seeking a Branch Manager for its Kisumu main branch. You will lead branch operations, drive business growth, manage staff, and ensure excellent customer service for one of KCB's key Western Kenya branches.",
    requirements: ["Bachelor's degree in Business, Finance, or related", "5+ years in banking, with 2+ in branch management", "Strong leadership and business development skills", "Knowledge of banking products and credit operations", "Understanding of the Western Kenya market"],
    responsibilities: ["Lead branch operations and team", "Drive deposit mobilization and lending targets", "Manage customer relationships and service quality", "Ensure compliance with banking regulations", "Prepare branch performance reports"],
    highlights: ["Branch management role", "Performance-based bonus", "Medical insurance", "Housing allowance", "Career progression to regional management"],
    deadlineDays: 21,
  },
  {
    title: "Agricultural Extension Officer",
    companySlug: "twiga-foods",
    location: "Nakuru",
    category: "NONPROFIT",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    employmentType: "PERMANENT",
    salaryMin: 35000, salaryMax: 50000, showSalary: true,
    about: "Twiga Foods is hiring Agricultural Extension Officers for its farmer engagement programs in Nakuru county. You will train farmers on best agricultural practices, post-harvest handling, and market linkage through Twiga's platform.",
    requirements: ["Diploma in Agriculture, Agribusiness, or Extension", "Knowledge of crop production and post-harvest handling", "Community mobilization skills", "Motorcycle riding license", "Willingness to work in rural areas"],
    responsibilities: ["Train farmers on agricultural best practices", "Coordinate farmer group meetings and demonstrations", "Collect and report farm-level data", "Link farmers to Twiga's marketplace", "Monitor program adoption and impact"],
    highlights: ["Community impact work", "Motorcycle and fuel allowance", "Medical insurance", "Field training provided", "Growing agri-tech sector"],
    deadlineDays: 10,
  },
];

module.exports = { JOBS, htmlDesc, makeSlug };
