// Mock opportunities data for the Opportunities listing page
export const opportunityTypes = [
  "All",
  "Scholarships",
  "Grants",
  "Fellowships",
  "Bursaries",
  "Competitions",
  "Conferences",
  "Volunteer",
  "Apprenticeships",
];

export const mockOpportunities = [
  {
    id: 1,
    title: "Mastercard Foundation Scholars Program 2026 — Fully Funded",
    slug: "mastercard-foundation-scholars-2026",
    organizationName: "Mastercard Foundation",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-08-15",
    value: "Fully Funded",
    description:
      "Full scholarships for African students pursuing undergraduate studies at partner universities across Africa.",
    location: "Multiple Countries",
    isFeatured: true,
    isNew: false,
  },
  {
    id: 2,
    title: "Google AI First Africa Scholarship 2026",
    slug: "google-ai-first-africa-scholarship",
    organizationName: "Google",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-07-30",
    value: "Fully Funded",
    description:
      "Learn AI/ML skills through Google's scholarship program. Open to Kenyan students and developers.",
    location: "Kenya (Online)",
    isFeatured: true,
    isNew: true,
  },
  {
    id: 3,
    title: "USAID Kenya Innovation Grant — Up to KSh 5M",
    slug: "usaid-kenya-innovation-grant",
    organizationName: "USAID Kenya",
    opportunityType: "Grant",
    type: "grant",
    deadline: "2026-06-30",
    value: "Up to KSh 5M",
    description:
      "Funding for innovative tech solutions addressing development challenges in Kenya.",
    location: "Kenya",
    isFeatured: false,
    isNew: true,
  },
  {
    id: 4,
    title: "Aga Khan Foundation International Scholarship",
    slug: "aga-khan-foundation-international-scholarship",
    organizationName: "Aga Khan Foundation",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-09-01",
    value: "50% — 100% Tuition",
    description:
      "Postgraduate scholarships for outstanding students from developing countries.",
    location: "International",
    isFeatured: false,
    isNew: false,
  },
  {
    id: 5,
    title: "Mandela Washington Fellowship 2026",
    slug: "mandela-washington-fellowship-2026",
    organizationName: "U.S. Department of State",
    opportunityType: "Fellowship",
    type: "fellowship",
    deadline: "2026-10-15",
    value: "Fully Funded",
    description:
      "Six-week leadership program in the U.S. for young African leaders in business, civic engagement, and public management.",
    location: "United States",
    isFeatured: true,
    isNew: false,
  },
  {
    id: 6,
    title: "Nairobi County Bursary Fund 2026/2027",
    slug: "nairobi-county-bursary-fund-2026",
    organizationName: "Nairobi County Government",
    opportunityType: "Bursary",
    type: "bursary",
    deadline: "2026-05-31",
    value: "KSh 10,000 — KSh 30,000",
    description:
      "Financial aid for needy students in Nairobi County pursuing secondary and tertiary education.",
    location: "Nairobi, Kenya",
    isFeatured: false,
    isNew: false,
  },
  {
    id: 7,
    title: "Microsoft Africa Development Centre Fellowship",
    slug: "microsoft-africa-development-centre-fellowship",
    organizationName: "Microsoft",
    opportunityType: "Fellowship",
    type: "fellowship",
    deadline: "2026-07-15",
    value: "Paid — $2,000/mo",
    description:
      "12-month engineering fellowship for software developers at Microsoft's Africa Development Centre in Nairobi.",
    location: "Nairobi, Kenya",
    isFeatured: false,
    isNew: true,
  },
  {
    id: 8,
    title: "Safaricom Hackathon 2026 — KSh 1M Prize",
    slug: "safaricom-hackathon-2026",
    organizationName: "Safaricom PLC",
    opportunityType: "Competition",
    type: "competition",
    deadline: "2026-06-15",
    value: "KSh 1M Prize",
    description:
      "Annual hackathon challenging developers to build innovative solutions using Safaricom APIs and platforms.",
    location: "Nairobi, Kenya",
    isFeatured: false,
    isNew: true,
  },
  {
    id: 9,
    title: "Tech Summit Nairobi 2026 — Free Tickets",
    slug: "tech-summit-nairobi-2026",
    organizationName: "TechSummit Africa",
    opportunityType: "Conference",
    type: "conference",
    deadline: "2026-04-20",
    value: "Free Entry",
    description:
      "East Africa's largest tech conference featuring keynotes from global tech leaders, workshops, and networking.",
    location: "Nairobi, Kenya",
    isFeatured: false,
    isNew: false,
  },
  {
    id: 10,
    title: "Kenya Red Cross Volunteer Program 2026",
    slug: "kenya-red-cross-volunteer-program",
    organizationName: "Kenya Red Cross Society",
    opportunityType: "Volunteer",
    type: "volunteer",
    deadline: "2026-12-31",
    value: "Volunteer",
    description:
      "Join Kenya's largest humanitarian organization. Various roles available in disaster response, health, and community outreach.",
    location: "Nationwide, Kenya",
    isFeatured: false,
    isNew: false,
  },
  {
    id: 11,
    title: "Equity Group Foundation Wings to Fly Scholarship",
    slug: "equity-wings-to-fly-scholarship",
    organizationName: "Equity Group Foundation",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-06-01",
    value: "Fully Funded",
    description:
      "Comprehensive scholarship covering tuition, accommodation, and upkeep for academically gifted but financially needy students.",
    location: "Kenya",
    isFeatured: true,
    isNew: false,
  },
  {
    id: 12,
    title: "Electrical Apprenticeship — Kenya Power 2026",
    slug: "kenya-power-electrical-apprenticeship",
    organizationName: "Kenya Power & Lighting Company",
    opportunityType: "Apprenticeship",
    type: "apprenticeship",
    deadline: "2026-05-15",
    value: "Stipend — KSh 25,000/mo",
    description:
      "2-year hands-on electrical apprenticeship program with Kenya Power. Gain practical experience in power distribution and maintenance.",
    location: "Nairobi, Kenya",
    isFeatured: false,
    isNew: false,
  },
];

export const featuredOpportunities = mockOpportunities.filter((o) => o.isFeatured);

// Related hubs for sidebar
export const relatedHubs = [
  { slug: "scholarships", name: "Scholarships", count: 45 },
  { slug: "grants", name: "Grants & Funding", count: 23 },
  { slug: "fellowships", name: "Fellowships", count: 18 },
  { slug: "bursaries", name: "Bursaries", count: 31 },
  { slug: "competitions", name: "Competitions", count: 12 },
  { slug: "volunteer", name: "Volunteer", count: 27 },
];

// Stats for the hero section
export const opportunityStats = {
  totalOpportunities: 156,
  thisMonth: 23,
  deadlineSoon: 8,
  providers: 89,
};
