// Full mock article data for the blog article detail page
export const article = {
  slug: "how-to-write-cv-kenya-2026",
  title: "How to Write a CV That Gets You Interviewed in Kenya — Complete 2026 Guide",
  subtitle:
    "The ultimate guide to writing a CV that passes ATS systems, impresses Kenyan recruiters, and lands you more interviews.",
  category: "CV Tips",
  categorySlug: "cv-tips",
  author: {
    name: "Grace Wanjiku",
    initials: "GW",
    title: "Senior Career Coach",
    bio: "Certified career coach with 10+ years of experience helping Kenyan professionals land their dream jobs. Specializes in CV writing, interview coaching, and career transitions for both entry-level and senior professionals.",
    linkedin: "https://linkedin.com/in/grace-wanjiku",
    twitter: "https://twitter.com/gracewanjiku",
    articles: 28,
    coached: "3,000+",
    views: "185K",
  },
  publishedAt: "2026-01-15T09:00:00+03:00",
  updatedAt: "2026-03-20T14:30:00+03:00",
  readingTime: "12 min read",
  viewsCount: 14230,
  wordCount: 2800,
  tags: ["CV Writing", "Job Search", "ATS", "Kenya Jobs", "Career Advice", "Templates"],
  tableOfContents: [
    { id: "why-cv-matters", title: "Why Your CV Matters More Than You Think" },
    { id: "understanding-ats", title: "Understanding ATS Systems in Kenya" },
    { id: "perfect-structure", title: "The Perfect CV Structure for 2026" },
    { id: "writing-each-section", title: "Step-by-Step: Writing Each Section" },
    { id: "common-mistakes", title: "10 Common CV Mistakes Kenyan Job Seekers Make" },
    { id: "free-templates", title: "Free CV Templates for Kenyan Job Seekers" },
    { id: "tailor-cv", title: "How to Tailor Your CV for Each Application" },
    { id: "professional-vs-diy", title: "Professional CV Writing vs. DIY" },
    { id: "final-checklist", title: "Final CV Checklist Before Applying" },
  ],
};

export const relatedArticles = [
  {
    slug: "common-cv-mistakes-kenyan-job-seekers",
    title: "10 Common CV Mistakes Kenyan Job Seekers Make",
    category: "CV Tips",
    readingTime: "5 min read",
    viewsCount: 8930,
    gradient: "bg-gradient-to-r from-blue-600 to-blue-400",
    pillColor: "bg-blue-100 text-blue-700",
  },
  {
    slug: "cover-letter-templates-kenya",
    title: "Cover Letter Templates That Actually Work in Kenya",
    category: "CV Tips",
    readingTime: "4 min read",
    viewsCount: 7810,
    gradient: "bg-gradient-to-r from-blue-600 to-blue-400",
    pillColor: "bg-blue-100 text-blue-700",
  },
  {
    slug: "safaricom-panel-interview-prep",
    title: "How to Prepare for a Safaricom Panel Interview",
    category: "Interview Prep",
    readingTime: "8 min read",
    viewsCount: 6750,
    gradient: "bg-gradient-to-r from-emerald-600 to-emerald-400",
    pillColor: "bg-emerald-100 text-emerald-700",
  },
];
