// Mock search results data for the Search Results page
export const mockJobResults = [
  {
    id: 1,
    title: "Senior Accountant",
    slug: "senior-accountant-safaricom",
    company: {
      name: "Safaricom PLC",
      slug: "safaricom",
      logoColor: "#00a254",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Mid-Senior",
    publishedAt: "2026-03-28",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    excerpt:
      "Lead financial reporting and compliance for Kenya's largest telecom. CPA-K required, 5+ years experience in a listed company.",
    highlights: ["CPA-K", "Health Insurance", "Performance Bonus"],
  },
  {
    id: 2,
    title: "Financial Analyst",
    slug: "financial-analyst-equity",
    company: {
      name: "Equity Bank",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Entry Level",
    publishedAt: "2026-03-27",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    excerpt:
      "Analyze financial data, prepare reports, and support strategic decision-making. Bachelor's degree in Finance or Accounting required.",
    highlights: ["IFRS", "Excel", "Medical Cover"],
  },
  {
    id: 3,
    title: "Audit Manager",
    slug: "audit-manager-kcb",
    company: {
      name: "KCB Group",
      slug: "kcb-group",
      logoColor: "#059669",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Senior",
    publishedAt: "2026-03-26",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    excerpt:
      "Oversee internal audit operations across banking subsidiaries. CPA-K or ACCA, 7+ years in audit.",
    highlights: ["CPA-K", "ACCA", "Leadership Role"],
  },
  {
    id: 4,
    title: "Accounts Payable Officer",
    slug: "accounts-payable-officer-kpmg",
    company: {
      name: "KPMG Kenya",
      slug: "kpmg-kenya",
      logoColor: "#1a56db",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Entry Level",
    publishedAt: "2026-03-25",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    excerpt:
      "Process vendor payments, reconcile accounts, and maintain accurate financial records. QuickBooks experience a plus.",
    highlights: ["QuickBooks", "Sage", "Entry Level"],
  },
  {
    id: 5,
    title: "Tax Consultant",
    slug: "tax-consultant-pwc",
    company: {
      name: "PwC Kenya",
      slug: "pwc-kenya",
      logoColor: "#dc2626",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Contract",
    experienceLevel: "Mid-Senior",
    publishedAt: "2026-03-24",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    excerpt:
      "Provide tax advisory services to multinational clients. CPA-K and 4+ years tax experience required.",
    highlights: ["CPA-K", "Tax Advisory", "KRA"],
  },
  {
    id: 6,
    title: "Finance Graduate Trainee",
    slug: "finance-graduate-trainee-britam",
    company: {
      name: "Britam Holdings",
      slug: "britam-holdings",
      logoColor: "#7c3aed",
      isVerified: true,
    },
    location: "Nairobi",
    jobType: "Full-Time",
    experienceLevel: "Entry Level",
    publishedAt: "2026-03-23",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    excerpt:
      "12-month rotational graduate program across finance departments. Recent bachelor's degree in Finance, Accounting, or Economics.",
    highlights: ["Graduate Program", "Mentorship", "Training"],
  },
];

export const mockOpportunityResults = [
  {
    id: 101,
    title: "CPA-K Study Scholarship — Strathmore University",
    slug: "cpa-k-study-scholarship-strathmore",
    organizationName: "Strathmore University",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-06-30",
    value: "Fully Funded",
    description: "Full scholarship for CPA-K course at Strathmore University.",
  },
  {
    id: 102,
    title: "IFRS Certification Grant for Kenyan Accountants",
    slug: "ifrs-certification-grant",
    organizationName: "ICPAK",
    opportunityType: "Grant",
    type: "grant",
    deadline: "2026-05-15",
    value: "KSh 150,000",
    description: "Financial support for IFRS certification for practicing accountants.",
  },
  {
    id: 103,
    title: "Accounting & Finance Fellowship — KRA",
    slug: "accounting-finance-fellowship-kra",
    organizationName: "Kenya Revenue Authority",
    opportunityType: "Fellowship",
    type: "fellowship",
    deadline: "2026-07-01",
    value: "Paid — KSh 80,000/mo",
    description: "6-month professional fellowship in tax policy and revenue management.",
  },
  {
    id: 104,
    title: "KASNEB Bursary for Accounting Students",
    slug: "kasneb-bursary-accounting-students",
    organizationName: "KASNEB",
    opportunityType: "Bursary",
    type: "bursary",
    deadline: "2026-04-30",
    value: "KSh 20,000",
    description: "Financial assistance for students sitting KASNEB professional exams.",
  },
];

// Search filter options
export const filterOptions = {
  jobType: [
    { label: "Full-Time", count: 28 },
    { label: "Part-Time", count: 8 },
    { label: "Contract", count: 6 },
    { label: "Internship", count: 3 },
    { label: "Remote", count: 2 },
  ],
  experienceLevel: [
    { label: "Entry Level", count: 12 },
    { label: "Mid-Senior", count: 18 },
    { label: "Senior", count: 10 },
    { label: "Manager/Director", count: 5 },
  ],
  datePosted: ["Last 24 hours", "Last 7 days", "Last 30 days", "Any time"],
  location: [
    { label: "Nairobi", count: 32 },
    { label: "Mombasa", count: 8 },
    { label: "Kisumu", count: 4 },
    { label: "Nakuru", count: 3 },
    { label: "Remote", count: 2 },
  ],
  company: [
    { label: "Safaricom", count: 12 },
    { label: "Equity Bank", count: 9 },
    { label: "KCB Group", count: 7 },
    { label: "KPMG", count: 5 },
    { label: "PwC", count: 4 },
  ],
  category: [
    { label: "Accounting & Finance", count: 18 },
    { label: "Banking", count: 12 },
    { label: "Audit & Compliance", count: 8 },
    { label: "Tax & Advisory", count: 5 },
    { label: "Insurance", count: 4 },
  ],
};

// Trending searches for sidebar
export const trendingSearches = [
  { query: "accountant jobs in Nairobi", count: 1240 },
  { query: "accounting internship Kenya", count: 890 },
  { query: "audit manager jobs", count: 670 },
  { query: "finance graduate trainee", count: 540 },
  { query: "CPA-K jobs", count: 430 },
  { query: "part-time accounting jobs", count: 310 },
];

// Popular tags
export const popularTags = [
  "CPA-K",
  "IFRS",
  "Excel",
  "QuickBooks",
  "Banking",
  "Audit",
  "Payroll",
  "Sage",
  "Tax Advisory",
  "Financial Analysis",
];
