// Mock data for the homepage — used when the database is empty.

export const trendingJobs = [
  {
    id: 1,
    slug: "senior-software-engineer-safaricom-plc",
    title: "Senior Software Engineer",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 2,
    slug: "marketing-director-equity-bank",
    title: "Marketing Director",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Equity Bank Kenya",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
  },
  {
    id: 3,
    slug: "data-scientist-kcb-group",
    title: "Data Scientist",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "KCB Group",
      slug: "kcb-group",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
  {
    id: 4,
    slug: "engineer-trainee-kenya-power",
    title: "Engineer Trainee",
    location: "Nationwide",
    jobType: "Internship",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: false,
    isUrgent: true,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Kenya Power",
      slug: "kenya-power",
      logoColor: "#059669",
      isVerified: false,
    },
  },
];

export const latestJobs = [
  {
    id: 5,
    slug: "software-engineer-backend-java-safaricom",
    title: "Software Engineer — Backend (Java)",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 6,
    slug: "graphic-design-intern-ogilvy-kenya",
    title: "Graphic Design Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Ogilvy Kenya",
      slug: "ogilvy-kenya",
      logoColor: "#e74c3c",
      isVerified: false,
    },
  },
  {
    id: 7,
    slug: "accountant-county-government-kiambu",
    title: "Accountant",
    location: "Kiambu",
    jobType: "Full-time",
    experienceLevel: "Mid",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "County Government of Kiambu",
      slug: "county-gov-kiambu",
      logoColor: "#2563eb",
      isVerified: false,
    },
  },
  {
    id: 8,
    slug: "customer-service-representative-mombasa",
    title: "Customer Service Representative",
    location: "Mombasa",
    jobType: "Full-time",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "CCK Call Centres",
      slug: "cck-call-centres",
      logoColor: "#8b5cf6",
      isVerified: false,
    },
  },
  {
    id: 9,
    slug: "project-manager-unep-nairobi",
    title: "Project Manager — Climate Adaptation",
    location: "Nairobi",
    jobType: "Contract",
    experienceLevel: "Senior",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "UNEP Kenya",
      slug: "unep-kenya",
      logoColor: "#009688",
      isVerified: true,
    },
  },
  {
    id: 10,
    slug: "nursing-officer-kenyatta-hospital",
    title: "Nursing Officer — ICU",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Kenyatta National Hospital",
      slug: "kenyatta-hospital",
      logoColor: "#dc2626",
      isVerified: true,
    },
  },
];

export const featuredJobs = [
  {
    id: 11,
    slug: "product-manager-m-pesa-safaricom",
    title: "Product Manager — M-PESA",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Senior",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Safaricom PLC",
      slug: "safaricom-plc",
      logoColor: "#00a254",
      isVerified: true,
    },
  },
  {
    id: 12,
    slug: "head-of-digital-banking-equity",
    title: "Head of Digital Banking",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Manager",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Equity Bank",
      slug: "equity-bank",
      logoColor: "#f59e0b",
      isVerified: true,
    },
  },
  {
    id: 13,
    slug: "risk-analyst-kcb-group",
    title: "Risk Analyst",
    location: "Nairobi",
    jobType: "Full-time",
    experienceLevel: "Mid",
    isFeatured: true,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "KCB Group",
      slug: "kcb-group",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
];

export const internshipJobs = [
  {
    id: 14,
    slug: "kra-internship-programme-2026",
    title: "Internship Programme 2026",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: false,
    isUrgent: true,
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Kenya Revenue Authority",
      slug: "kra",
      logoColor: "#1a56db",
      isVerified: true,
    },
  },
  {
    id: 15,
    slug: "finance-intern-britam",
    title: "Finance Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: true,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "Britam Holdings",
      slug: "britam",
      logoColor: "#7c3aed",
      isVerified: false,
    },
  },
  {
    id: 16,
    slug: "it-support-intern-ncba",
    title: "IT Support Intern",
    location: "Nairobi",
    jobType: "Internship",
    experienceLevel: "Entry",
    isFeatured: false,
    isNew: false,
    isUrgent: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    company: {
      name: "NCBA Group",
      slug: "ncba-group",
      logoColor: "#059669",
      isVerified: true,
    },
  },
];

export const urgentDeadlines = [
  {
    id: 14,
    slug: "kra-internship-programme-2026",
    title: "Internship Programme 2026",
    company: "Kenya Revenue Authority",
    deadline: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 17,
    slug: "m-e-consultant-undp-kenya",
    title: "Monitoring & Evaluation Consultant",
    company: "UNDP Kenya",
    deadline: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 18,
    slug: "civil-engineer-county-nakuru",
    title: "Civil Engineer — Infrastructure",
    company: "County Government of Nakuru",
    deadline: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
  },
];

export const sidebarDeadlines = [
  { name: "KRA Internship", timeLeft: "4h 23m" },
  { name: "UNDP Consultant", timeLeft: "1d 5h" },
  { name: "County Gov Nakuru", timeLeft: "2d 12h" },
  { name: "PSC Admin Officer", timeLeft: "5d 8h" },
  { name: "Mastercard Foundation", timeLeft: "12d" },
];

export const categories = [
  { name: "Technology", count: 342, href: "/jobs/technology", color: "#1a56db", icon: "FiMonitor" },
  { name: "Finance & Accounting", count: 256, href: "/jobs/finance-accounting", color: "#059669", icon: "FiDollarSign" },
  { name: "Engineering", count: 189, href: "/jobs/engineering", color: "#f59e0b", icon: "FiTool" },
  { name: "Healthcare", count: 234, href: "/jobs/healthcare", color: "#dc2626", icon: "FiHeart" },
  { name: "Education", count: 167, href: "/jobs/education", color: "#7c3aed", icon: "FaGraduationCap" },
  { name: "Marketing", count: 198, href: "/jobs/sales-marketing", color: "#ec4899", icon: "FaChartLine" },
  { name: "Government", count: 412, href: "/jobs/government", color: "#1e40af", icon: "FiFlag" },
  { name: "NGO & International", count: 156, href: "/jobs/ngo", color: "#009688", icon: "FiGlobe" },
];

export const opportunities = [
  {
    title: "Mastercard Foundation Scholars Programme",
    slug: "mastercard-foundation-scholars",
    organizationName: "Mastercard Foundation",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2026-12-15",
    value: "Full tuition + stipend",
  },
  {
    title: "Kenya Government Bursary 2026",
    slug: "kenya-government-bursary-2026",
    organizationName: "Ministry of Education",
    opportunityType: "Bursary",
    type: "bursary",
    deadline: "2026-11-30",
    value: "Apply via Constituency",
  },
  {
    title: "DAAD Scholarships — Germany",
    slug: "daad-scholarships-germany",
    organizationName: "DAAD — German Academic Exchange",
    opportunityType: "Scholarship",
    type: "scholarship",
    deadline: "2027-01-15",
    value: "Masters / PhD",
  },
];

export const topEmployers = [
  { name: "Safaricom PLC", slug: "safaricom-plc", jobCount: 45, logoColor: "#00a254" },
  { name: "KCB Group", slug: "kcb-group", jobCount: 32, logoColor: "#1a56db" },
  { name: "Equity Bank", slug: "equity-bank", jobCount: 28, logoColor: "#f59e0b" },
  { name: "KRA", slug: "kra", jobCount: 15, logoColor: "#1a56db" },
  { name: "PwC Kenya", slug: "pwc-kenya", jobCount: 12, logoColor: "#7c3aed" },
  { name: "UNDP Kenya", slug: "undp-kenya", jobCount: 9, logoColor: "#009688" },
];

export const sidebarFeaturedJobs = [
  {
    title: "Product Manager — M-PESA",
    slug: "product-manager-m-pesa-safaricom",
    company: "Safaricom PLC",
    location: "Nairobi",
    logoColor: "#00a254",
  },
  {
    title: "Branch Manager — Kisumu",
    slug: "branch-manager-kisumu-equity",
    company: "Equity Bank",
    location: "Kisumu",
    logoColor: "#f59e0b",
  },
  {
    title: "Audit Associate",
    slug: "audit-associate-pwc",
    company: "PwC Kenya",
    location: "Nairobi",
    logoColor: "#7c3aed",
  },
  {
    title: "Data Engineer",
    slug: "data-engineer-kcb",
    company: "KCB Group",
    location: "Nairobi",
    logoColor: "#1a56db",
  },
];

export const trustedLogos = [
  "Safaricom",
  "Equity Bank",
  "KCB Group",
  "KRA",
  "UNDP Kenya",
  "Kenya Power",
  "NCBA",
];

export const quickLinks = [
  { label: "Internships", href: "/jobs/internships" },
  { label: "Govt Jobs", href: "/jobs/government" },
  { label: "Remote", href: "/jobs/remote" },
  { label: "Part-Time", href: "/jobs/part-time" },
  { label: "Scholarships", href: "/opportunities/scholarships" },
];

export const locations = [
  { label: "Nairobi", href: "/jobs/nairobi" },
  { label: "Mombasa", href: "/jobs/mombasa" },
  { label: "Kisumu", href: "/jobs/kisumu" },
  { label: "Nakuru", href: "/jobs/nakuru" },
  { label: "Remote", href: "/jobs/remote", highlight: true },
];
